workflows/imagery/standardising.yaml

This change in the `standardising` workflow enable running the standardise step on a specified S3 path containing image files so each image can be processed in parallel.
- A new task `aws-list` calling the `basemaps CLI` `list` command is executed prior to deploy one job per file returned - in parallel
- A new parameter `filter` has been added which allows to filter the files in the `uri` path using `RegExp`
- A new parameter `output` has been added which is used to determine where the processed files will be uploaded.
> **_NOTE:_**  The current `standardising.py` script called by the task `standardise` allows only one file per execution. A functionality allowing to pass a list of files will be implemented in the future.

feat(workflows/imagery): run standardise step on multiple files in parallel (TDE-303)

---

workflows/basemaps/list.yaml

as there are a number of other services running in the EKS cluster (eg kube system) we cannot just forward all logs as JSON. We can configure our jobs to use a JSON parser when running. which will extract JSON values from the `log` field and store them in `data.*`

feat: forward logs as JSON

---

workflows/imagery/standardising.yaml

remove output as parameter and upload tmp output to artifacts bucket.
relates to: https://github.com/linz/topo-imagery/pull/61

feat: use artifacts bucket instead of output

---

workflows/imagery/non-visual-qa.yaml

In order to use the `non_visual_qa.py` script from `Topo-Imagery`, we need a workflow template that allows us to submit a workflow from Argo.
Add the workflow template `non-visual-qa.yaml`
The workflow template has been created in Argo `imagery-non-visual-qa-l9z66` under the namespace `argo`.

feat(imagery): Non Visual QA workflow-template TDE-309

---

workflows/imagery/standardising.yaml

Fixing up the requested resources to use the default for the file listing and bumping up the CPU to 4000m for the `gdal_translate`.

fix: standardising workflowtemplate requested resources

---

workflows/imagery/standardising.yaml

the machines are only spawning with ~12GB of usable storage, so it will limit to 1 pod per machine.

fix: lower storage limits, move the standardise to spot and align cpu/memory requests

---

workflows/imagery/standardising.yaml
workflows/test/sleep.yml

developers can submit the workflow then use kubectl to connect to the machine.
```
argo submit workflows/test/sleep.yml
k exec -it sleep-:podName /bin/bash
```

feat: workflow that sleeps for a hour for testing

---

workflows/imagery/standardise-only.yaml

The `imagery-standardising` workflow should include the non visual qa process. The non visual qa process has been added as a second step running after the standardising script in `topo-imagery` via `standardise_validate.py` script.
- Rename workflow templace to `imagery-standardising-`
- Call the `standardise_validate.py` instead of the `standardising.py` script
- Create a workflow template `imagery-standardise-only-` that calls only `standardising.py` script
> **_NOTE:_**  Both workflow templates have been deployed in Argo.

feat: add non visual qa in imagery-standardising workflow TDE-450

---

workflows/imagery/standardising.yaml

Unless we want to see the parameters for each pods in the Argo UI - we can still see them in the main pod, I feel it's not necessary to pass the parameters from the user input to the task to the template and that adds some complexity in the `yaml` file.

refactor: simplify parameters passing in standardising workflow

---

workflows/stac/stac-validate.yaml

The output does not display very nicely in Argo, so there may be a better way to do that.

feat: stac-validate workflow TDE-499

---

workflows/imagery/standardising.yaml

example output: `s3://linz-workflow-artifacts/2022-10/09-mdavidson-test-imagery-standardising-nk44q/mdavidson-test-imagery-standardising-nk44q-82035514/tmp/`
example stac item file (converted to txt as github wouldn't allow json): [BX24_5000_0407.txt](https://github.com/linz/topo-workflows/files/9742594/BX24_5000_0407.txt)

feat: update standardising workflow to create stac items TDE-492

---

workflows/imagery/standardising.yaml

standardising workflow failed with OOMKilled

fix: increase memory

---

workflows/test/flatten.yaml

`500` is too big, `30` seems reliable for a temporary fix.

fix: change default flatten group size

---

workflows/imagery/non-visual-qa.yaml
workflows/imagery/standardising.yaml
workflows/imagery/tests.yaml

This contains the topo-imagery fix to specify and check the number of bands.

chore: bump topo-imagery container to v0.2.0-49

---

workflows/basemaps/mapsheet-json.yaml
workflows/imagery/extent.yaml
workflows/imagery/non-visual-qa.yaml
workflows/imagery/standardising.yaml
workflows/stac/stac-validate.yaml
workflows/test/flatten.yaml
workflows/test/list.yaml

`argo-task` `copy` command has two new parameters `--no-clobber` and `--force`. The way the container is build has changed as well, so needed to update the command entry point.

feat: update argo-task version and add new copy parameter

---

workflows/imagery/standardising.yaml

stac validation failed as the description was empty. 
(https://argo.linzaccess.com/workflows/argo/imagery-standardising-v0.2.0-52-t49z9?tab=workflow) 
Removing `value: ""` from these parameters means the user has to input a value when submitting the workflow.
Otherwise argo will give an error that lets the user know it is required.

fix: remove title and description values

---

workflows/imagery/extent.yaml
workflows/imagery/non-visual-qa.yaml
workflows/imagery/publish-copy.yaml
workflows/imagery/publish-imagery.yaml
workflows/imagery/standardising.yaml
workflows/stac/stac-validate.yaml
workflows/test/flatten.yaml
workflows/test/list.yaml

- Changes to the `flatten` argo-task to allow it to copy to and from other locations.
- `standardising` has been updated for this change.
- New `publish-copy` workflow for publishing from Argo Tasks `flat` directory to `linz-imagery` and RGBI from `linz-imagery-upload` to `linz-imagery-staging`.
- `argo-tasks` container version bumped up to the latest version.
- `imagery` workflows changed to use latest `config.json`

feat: Publish Workflow TDE-494

---

workflows/imagery/tests.yaml

`test-` are not alerted on `#alert-argo-workflows`

chore: rename test script to avoid alert on Slack main channel

---

workflows/imagery/standardising.yaml

- Updates the basemaps/cli container version.
- Reverts the workflow version number back to `v0.2.0-75` to keep it in sync with the topo-imagery container. Version number was previously incremented to `v0.2.0-76` in #80 as I was unaware of the convention of keeping the standardising workflow and topo-imagery container version numbers in sync.

chore: update basemaps/cli container version and revert version number

---

workflows/basemaps/create-config.yaml
workflows/basemaps/create-overview-all.yaml
workflows/basemaps/create-overview.yaml
workflows/basemaps/imagery-import.yaml
workflows/basemaps/mapsheet-json.yaml
workflows/imagery/standardising.yaml

Now `basemaps` uses major version tags!
https://github.com/linz/basemaps/pkgs/container/basemaps%2Fcli

feat: use major version for basemaps

---

workflows/imagery/standardising.yaml

- Add standardising outputs in preparation for using the output for the new standardising-publish workflow.
- Wrap the container variables in quotes as otherwise they don't resolve when sent through from a workflow.

feat: add standardising output TDE-615

---

workflows/basemaps/mapsheet-json.yaml

It can now download multiple files and so it stores the file in a target folder rather than a target single file.

fix: use the new cli arguments for lds-fetch-layer

---

workflows/basemaps/mapsheet-json.yaml

since the geopackage does not have a fixed name, a glob "*.gpkg" is a good way of allowing ogr to find it.
however globbing is done by the shell, so switching to "sh" as the command allows the glob to expand then pass it into ogr2ogr

fix: use sh to allow path globbing to find the geopackage

---

workflows/imagery/README.md
workflows/imagery/standardising.yaml

Add a new parameter `licensor-list` that allows the user to pass multiple STAC `licensor` names to create the `collection.json`.
This parameter is optional and does not have a control on the names passed. The list has to be separated by semicolon `;` and takes effect only if there are more than 1 element, otherwise it's `licensor` (the dropdown list) that is used.
Related to https://github.com/linz/topo-imagery/pull/355

feat: optional parameter licensor-list TDE-643

---

workflows/basemaps/create-overview-all.yaml
workflows/basemaps/create-overview.yaml
workflows/imagery/standardising.yaml

Retry on create-overviews failure.
Basemaps CLI version needs to be set for the create-overview fix.
Can set it back to generic version after next `basemaps-cli` release.

fix: retry create overviews and fix basemaps-cli version

---

workflows/imagery/standardising.yaml

Since scale is optional for standardising imagery (https://github.com/linz/topo-imagery/pull/372)

feat: add optional scale TDE-674

---

workflows/stac/stac-validate.yaml

When using sprig function, needs to address the parameter differently: https://argoproj.github.io/argo-workflows/variables/#expression

fix: stac-validate fails on input parameter parsing

---

CONFIGURATION.md
workflows/basemaps/mapsheet-json.yaml
workflows/imagery/publish-copy.yaml
workflows/imagery/standardising.yaml
workflows/imagery/tests.yaml
workflows/imagery/tileset-validate.yaml
workflows/stac/stac-validate.yaml
workflows/test/env.yaml
workflows/test/flatten.yaml
workflows/test/list.yaml

update workflows to use ECR container versions of topo-imagery and argo-tasks
**Test run results:**
```
18m         Normal    Pulled                  pod/test-mdavidson-ecr-aws-list-2h2px-nf97p-aws-list-4146989921   Successfully pulled image "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-latest" in 15.565196347s
91s         Normal    Pulled                  pod/test-mdavidson-ecr-imagery-standardising-7tgtf-standardise-validate-678835351   Successfully pulled image "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:topo-imagery-latest" in 12.104966455s
91s         Normal    Pulled                  pod/test-mdavidson-ecr-imagery-standardising-7tgtf-standardise-validate-678835351   Successfully pulled image "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:topo-im …
```

feat: use ecr topo imagery containers

---

workflows/imagery/standardising.yaml

https://argoproj.github.io/argo-workflows/conditional-artifacts-parameters/
Argo workflow conditionals are evaluated as `govaluate` expressions: https://github.com/Knetic/govaluate/blob/master/MANUAL.md#regex-comparators--
Example:
https://argo.linzaccess.com/workflows/argo/test-mdavidson-imagery-standardising-t5kbl?tab=workflow

feat: restrict basemaps steps to certain epsg codes

---

workflows/basemaps/mapsheet-json.yaml
workflows/imagery/standardising.yaml

Starting to see 
> ImagePull: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/debian:latest": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/debian/manifests/sha256:63d62ae233b588d6b426b7b072d79d1306bfd02a72bff1fc045b8511cc89ee09: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

fix: use ecr/ghcr and not docker.io to bypass rate limit

---

workflows/imagery/standardising-publish-import.yaml

Adding two version updates that were missed in https://github.com/linz/topo-workflows/pull/142/files

fix: update versions on standardise-publish-import workflow TDE-784

---

templates/argo-tasks/tile-index-validate.yml

fix: increase resource memory for tile-index-validate task TDE-782

---

templates/argo-tasks/group.yml
templates/argo-tasks/tile-index-validate.yml

Argo will not automatically re-pull docker container with tags of `:argo-tasks-latest` or `:v2` which means sometimes containers will be older versions, the expected `:argo-tasks-latest` or `:v2`
This can cause stale containers to live for a long time on long running machines such as the controller nodes which are up for months at a time, sometimes causing very old containers to run.
All workflows need a `imagePullPolicy: Always` to force pull all containers, this will not download the container if it already exists it will only validate that the local hash is the same as the remote hash.

fix: force containers in templates to be pulled

---

config/semaphores.yml
workflows/imagery/publish-copy.yaml

To limit the number of publish-copy workflows that can run concurrently to 8

fix: add publish-copy bulkcopy semaphore

---

workflows/basemaps/imagery-import-cogify.yml

Changes the defaults for basemaps imagery import cogify workflow to be full s3:// locations.
The previous values were taken from the non-cogify import workflow, which used the `make-cog` command. This has a magic `--aws` flag which transforms the targets into s3:// bucket locations. The equivalent cogify commands on the other hand require the actual path itself.

feat: update default target values for basemaps import BM-822

---

workflows/basemaps/imagery-import-cogify.yml

Use `name` key not `generateName` in the metadata section for `basemaps-imagery-import-cogify` workflow template. This now matches the metadata sections for other workflow templates which use `name` not `generateName`.
While the yaml file passed `argo lint` and was able to be merged, it failed deployment to the argo server ([see build logs](https://github.com/linz/topo-workflows/actions/runs/5944408541/job/16121623608)) with the following error:
```
error: from basemaps-imagery-import-cogify-: cannot use generate name with apply
```

fix: update basemaps-imagery-import-cogify metadata for WorkflowTemplate BM-822

---

workflows/basemaps/imagery-import-cogify.yml

Adds ability for `basemaps-imagery-import-cogify` workflow to write to Basemaps buckets.
Testing was done outputting too `s3://linz-imagery-artifacts` so it was missed that the workflow did not have write permission to `s3://linz-basemaps`.
*If not applicable, provide explanation of why.*

feat: add write permissions for basemaps buckets BM-822

---

workflows/basemaps/imagery-import-cogify.yml

Fixes bucket permissions for `basemaps-imagery-import-cogify`.
Does what PR https://github.com/linz/topo-workflows/pull/159 aimed to do, but did not work, as multiple comma separated sources for role config files were not supported.
*If not applicable, provide explanation of why.*

feat: update permissions for cogify import workflow BM-822

---

workflows/topo-maps/create-thumbnails.yaml
workflows/util/README.md
workflows/util/create-thumbnails.yaml

Thumbnail workflow created for the processing of the topo50 and 250 maps
**971** topo50 thumbnails in 8m31s (including pod pending time):
- [workflow](https://argo.linzaccess.com/workflows/argo/generate-thumbnails-topo50-250-44q4g?tab=workflow&nodeId=artifact:s3:s3.amazonaws.com:linz-workflow-artifacts:2023-08/22-generate-thumbnails-topo50-250-44q4g/)
- `s3://linz-workflow-artifacts/2023-08/22-generate-thumbnails-topo50-250-44q4g/intermediate/`

feat: add thumbnail workflow for topo maps TDE-840

---

workflows/util/README.md
workflows/util/create-thumbnails.yaml

In order to filter on files to process, `include` can be useful.

feat: add include regex in create-thumbnails TDE-841

---

workflows/util/create-thumbnails.yaml

If a new release of Topo maps contains some already existing maps (already published), the resolution process is to overwrite the existing files.

feat: allow copy --force when moving maps and thumbnails TDE-841

---

workflows/imagery/publish-copy.yaml
workflows/imagery/publish-odr.yaml

This workflowtemplate can write to `nz-imagery` but has not yet been updated to push to `imagery` Github repo when the target is `s3://nz-imagery`.

feat: create publish workflow template for ODR TDE-801

---

workflows/imagery/publish-copy.yaml
workflows/imagery/publish-odr.yaml

Temporary separate ODR publishing workflow to publish to `nz-imagery` until we put an approval process in place.

feat: publish to github for nz-imagery target TDE-801

---

workflows/basemaps/imagery-import-cogify.yml

Cogify steps sometimes fail all steps should be retryable, so default to retrying twice.
We also saw some containers running out of memory so increase their memory requests but also increase the number of tiffs to process at once.

fix(cogify): retry all workflow steps and increase instance size

---

workflows/basemaps/imagery-import-cogify.yml

Cogify is running out of memory and running the disk out of IOPS adjust the requests to get a bigger share of each instance.

fix(cogify): adjust resource requests

---

workflows/basemaps/imagery-import-cogify.yml

We are still getting pods killed by `OOMKilled`, possibly caused by too many gdal_translates happening at the same time.
Remove memory `limits` and double the requested memory
Lower concurrency of gdal_translates to 2 per pod rather than 4 per pod

fix(cogify): lower concurrency and set resource limits to memory = 2x cpu

---

templates/argo-tasks/README.md
templates/argo-tasks/copy.yml
templates/argo-tasks/create-manifest.yml
templates/argo-tasks/push-to-github.yml
workflows/imagery/README.md
workflows/imagery/publish-copy.yaml
workflows/imagery/publish-odr.yaml

**Why:**
Currently the two workflows: `publish-odr` and `publish-copy` are almost direct copies of each other with a lot of duplicate code. This is a risk for future work as the same code will need to be updated in two different places, and it is likely to be forgotten/mistakes made. 
**Description:**
`copy`, `create-manifest` and `publish-to-github` have been pulled out into template workflow-templates that are each called by the tasks in `publish-copy` and `publish-odr`
The alternative option is to remove `publish-odr` and add it as options/parameters to `publish-copy`. I didn't do this as we had discussed wanting to make sure the odr was separate and the future possible enhancements of approval steps / restricting users who can run the workflow.

refactor: publish-copy & publish-odr TDE-868

---

workflows/imagery/ascii-standardise-publish.yaml
workflows/imagery/standardising.yaml

This workflow, converts all ascii files within a specified path to tiffs, it then runs standardising and publish as per normal on the translated data. 
~~Waiting for: https://github.com/linz/topo-imagery/pull/595~~
https://argo.linzaccess.com/workflows/argo/test-mdavidson-ascii9cc75?tab=workflow
sample output: `s3://linz-workflow-artifacts/mdavidson/canterbury/cheviot_2015/dem_1m/2193/`
**Example test:**
```bash
argo submit ~/dev/topo-workflows/workflows/imagery/ascii-standardise-publish.yaml -n argo -f ~/dev/topo-workflows/workflows/imagery/canterbury-test.yaml --generate-name test-ascii
```
`canterbury-test.yaml`:
```yaml
"source": "s3://linz-elevation-staging/lidar2/Canterbury_-_Cheviot_LiDAR_(2015)/Canterbury_-_Cheviot_LiDAR_1m_DEM_(2015)/"
"target": …
```

feat: translate ascii files prior to running standardise-publish TDE-814

---

workflows/imagery/standardising-publish-import.yaml

The merging of https://github.com/linz/topo-workflows/pull/161 linted against the old version of standardising so missed this required fix which broke Wentao's PR here: https://github.com/linz/topo-workflows/actions/runs/6333551973/job/17201837027?pr=179

fix: add source to workflow

---

.github/workflows/main.yml

The first `Lint workflows` is not testing against the workflows dependencies deployed in the same actions (as it's deployed after)...

ci: re-lint workflows after deployment

---

workflows/basemaps/vector-etl.yaml

Update the vector ETL to use the new create-pr cli in the argo-tasks. 
- Update to use new create-pr

feat(vector-etl): Update the vector etl workflow to use the new create-pr cli.

---

workflows/basemaps/create-config.yaml
workflows/imagery/standardising.yaml

Update the standerise workflow and create-config workflow to use cogify create-config
Updated standerise workflow and create-config workflow.
Update standerise workflow basemaps/cli version default to v6.

feat(basemaps): Update the standardise workflow and create-config workflow to use cogify create-config

---

templates/argo-tasks/copy.yml

The Argo Tasks copy command will register the first matching role, which in the case of 'linz-imagery' was the read role, causing copying to `linz-imagery` to fail.
It may be something that can be fixed in Argo Tasks or chunkd if there is a robust way to work out the naming/logic of the roles.
I also removed the default values as we probably want to explicitly specify the write roles in the upstream workflow.

fix: copy template bucket config ordering

---

config/README.md
config/eks/cluster.ts

Some resources need to interact with k8s and others directly with AWS so we are using both CDK and AWS-CDK. To enable resources to be deployed we need to scaffhold out the starting blocks such as namespaces so that service accounts can be deployed using AWS-CDK.
Create a structure for initial EKS / AWS deployments in CDK and start to define what components are in CDK vs CDK8s

feat: initial eks namespaces TDE-915

---

config/charts/karpenter.ts
config/imports/karpenter.k8s.aws.ts

There appears to be a bug with cdk8s unsing nested specs causing volumes to show as 
```
volumeSize:
value: 200Gi
```
the value key is invalid, doing the exact same source as a node template outpus
```
volumeSize: 200Gi
```
to work around the problem use a shared node template.
Adds a shared aws node template for both spot provisionsers to reference.

refactor: link both provisioners back to a shared node template

---

cdk8s.yaml
config/charts/kube-system.coredns.ts
docs/dns.configuration.md

When using `rewrite stop type AAAA A` DNS resolution would often hang for 30+seconds on the clients waiting for a response
Instantly respond to AAAA requests with a empty NOERROR to force clients to use A records for external hosts.

fix: use template rcode NOERROR to prevent timeouts

---

config/eks/cluster.ts

The Argo service account ARN stored in cloudformation was the fluentbit one (copiy-paste mistake).
Change it to the right Argo SA ARN

fix: argo sa arn is wrong

---

infra/util/cloud.formation.ts

Use syntatical sugar to reduce the number of explicit checks needed
- Uses modern javascript syntax sugar  
- Avoids using `!object` or `if(object)` to prevent type conversions

refactor: simplify cfn output logic

---

infra/README.md
infra/cdk8s.ts
infra/charts/argo.workflows.ts
infra/charts/fluentbit.ts
infra/charts/karpenter.ts
infra/constants.ts
infra/eks/cluster.ts

Deploy Argo Workflows using its Helm chart via CDK8s
Namespace and service accounts are managed in `aws-cdk`.
Helm Chart is deployed with CDK8s.

feat: cdk8s Argo Workflows TDE-904

---

README.md

Workflow logs are now in a specific group. See https://github.com/linz/aws-log-config/pull/790.
Update documentation related to the elastic search data view to use to see workflow logs.

docs: update elastic data view name for workflow logs TDE-921

---

infra/cdk8s.ts
infra/charts/cloudflared.ts

cloudflared was being deployed into the wrong namespace and using a invalid container link
corrects the namespace and container url.

fix: correct cloudflare namespace & container

---

infra/README.md

In order to use CDK8S `Helm` construct, the repository needs to be added in the local installation of Helm.
Add the add repositories to Helm step.

docs: add helm support step TDE-902

---

workflows/test/list.arm.yaml

I can never remember what the selectors and tolerations are to run ARM based workflows are so create a example workflow that runs on ARM SPOT
Example workflow to run on SPOT ARM nodes.

feat: example of running a workflow on spot arm nodes

---

infra/cdk.ts
infra/cdk8s.ts
infra/constants.ts
infra/eks/cluster.ts
infra/imports/karpenter.k8s.aws.ts
infra/imports/karpenter.sh.ts
tsconfig.json
workflows/test/list.arm.yaml

LINZ has a somewhat standard tsconfig which is relatively strict, we were not using it this attempts to bring this repo up to the stricter tsconfig
The stricter tsconfig requires
All imports end with `.js`, this prevents accidentaly importing directories with `import './foo'` where foo is either a `foo.js` or `foo/index.js`
No unchecked access to maps, this is more complicated as we now need to get a typescript type to say that even value in the CfnOutputs is in the `cfnOutputs` objects, I converted the validation to a `asserts` function guard and to simplify things made the all the CfnOutputKeys keys the same as their values.

build: add missing tsconfig

---

infra/cdk8s.ts
infra/charts/argo.extras.ts
infra/charts/argo.semaphores.ts

These semaphores need to exist for the workflow templates to run
Add the semaphores configmap to list of charts needing to be deployed.

fix: add missing semaphores config map

---

infra/util/labels.ts

Labels are useful for filtering, adding a repository label gives us the ability to see all infra that is deployed from this repository.
adds a label to all cdk8s deployed resources to include the git repository.

feat: add git repository location label

---

.github/workflows/main.yml
infra/README.md
infra/cdk.ts
infra/eks/arns.ts
infra/eks/cluster.ts

The CI user needs access to the AWS EKS cluster to deploy Workflows and configure the cluster.
Adds the CI user into EKS so it can make changes.

feat: give cicd role permissions on eks cluster

---

docs/infrastructure/kubernetes.version.md
infra/README.md
infra/eks/cluster.ts
package-lock.json
package.json

Kubernetes upgrades every quarter and to upgrade EKS is a few steps, we need this process to be well documented so we can upgrade frequently.
Upgrade EKS to 1.28 and document the steps that it took to upgrade.

feat: upgrade to kubernetes v1.28 TDE-916

---

infra/charts/fluentbit.ts

Fluentbit is not deployed on new nodes because of the karpenter provisioner taints.
Add a toleration to the daemon set matching the provisioner taints.

fix: fluentbit is not deployed on new nodes

---

infra/util/labels.ts

Deployments are broken as they use a label with a "/", labels cannot contain "/" in their value
> Service "fluentbit" is invalid: metadata.labels: Invalid value: "linz/topo-workflows": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Replaces the "/" in the label with "__"

fix: labels cannot contain "/"

---

docs/infrastructure/components/argo.workflows.md
docs/infrastructure/components/karpenter.md
docs/infrastructure/helm.md
docs/infrastructure/initial.deployment.md
infra/README.md

The infrastructure README is starting to get very cluttered with notes and tips, split the notes and components into their own files
Split more infrastructure docs into /docs

docs:  restructure to allow expansion on the components in use

---

workflows/basemaps/mapsheet-json.yaml

We relocate the create-mapsheet cli into argo-tasks.
- update the task to use argo-tasks container
- fix the exclude satellite name to align with the new basemaps-config naming convention.

feat(basemaps): Update create-mapsheet workflow to use the cli from argo tasks.

---

infra/cdk8s.ts
infra/constants.ts
infra/eks/cluster.ts

Creating the scratch bucket outside of the EKS stack will allow us to delete the cluster.
Remove the bucket creation from the EKS stack. Another PR in our internal infrastructure repository will be created to handle this bucket creation.

refactor: remove scratch bucket creation from eks stack TDE-930

---

docs/labels.md
infra/util/labels.ts

We use a number of undocumented labels across the kubernetes cluster to make it easier to find objects, this adds some background on the labels and how to use them
Add a document to explain the well known labels

docs: add docs on linz well known labels TDE-932

---

.github/workflows/main.yml

Github & JIRA have a great tracking mechanism for deployments to various environments to be consistent across LINZ use `prod` as the main production environment.
Splits deployments into a build -> deploy-prod flow and adds a prod environment 

ci: deploy into the prod environment BM-923

---

templates/argo-tasks/README.md
templates/argo-tasks/lint-inputs.yml
workflows/imagery/README.md
workflows/imagery/publish-copy.yaml
workflows/imagery/publish-odr.yaml

To be sure that the target paths in the publish workflows follow conventions by linting.
new linting step added to the start of `publish-copy` and `publish-odr`
This step can be skipped with the new parameter `skip-lint: 'true'`
~~- [ ] Tests updated~~ - there are no tests but the template was tested manually

feat: lint inputs before publish TDE-857

---

infra/eks/cluster.ts
package-lock.json
package.json

In order to test and ensure that [the upgrade procedure/doc](https://github.com/linz/topo-workflows/blob/master/docs/infrastructure/kubernetes.version.md) works
Downgrade Kubernetes

test: downgrade kubernetes version to deploy cluster TDE-916

---

docs/infrastructure/kubernetes.version.md
infra/eks/cluster.ts
package-lock.json
package.json

Testing [the process of upgrading Kubernetes](https://github.com/linz/topo-workflows/blob/master/docs/infrastructure/kubernetes.version.md#upgrade-kubernetes-versions).
- Upgrade Kubernetes in the Cluster stack so `cdk deploy` will upgrade the EKS cluster (ran the commands in the [doc](https://github.com/linz/topo-workflows/blob/master/docs/infrastructure/kubernetes.version.md#upgrade-steps)):
```
[~] AWS::Lambda::LayerVersion KubeCtlLayer KubeCtlLayerF044A2BC replace
├─ [~] Content (requires replacement)
│   └─ [~] .S3Key:
│       ├─ [-] 8e18eb5caccd2617fb76e648fa6a35dc0ece98c4681942bc6861f41afdff6a1b.zip
│       └─ [+] b4d47e4f1c5e8fc2df2cd474ede548de153300d332ba8d582b7c1193e61cbe1e.zip
├─ [~] Description (requires replacement)
│   ├─ [-] /opt/kubectl/kubectl 1.27; /opt/helm/helm 3.12
│ …
```

feat: upgrade k8s to test process TDE-916

---

.github/workflows/main.yml

I like using constants so I don't have to use find and replace and make mistakes.
Store the cluster name as a environment variable.

ci: store cluster name as env variable for re-use

---

.github/workflows/main.yml
.github/workflows/pull-request.yml

Make sure we run specific versions of actions, rather than moving tags.
Done with pin-github-action <https://github.com/mheap/pin-github-action> 1.8.0 using `npx pin-github-action .github/workflows/*.yml`.
Dependabot should support updating in the same fashion <https://github.com/dependabot/dependabot-core/issues/8277#issuecomment-1782819752>.

feat: Pin actions to hashes TDE-934

---

.github/workflows/main.yml
infra/__test__/arn.test.ts
infra/cdk.ts
infra/eks/arn.ts
infra/eks/cluster.ts
package.json

Maintainers should have direct access to the EKS Cluster.
Pass the maintainer role ARNs as a CDK context argument so they can be added as master on the cluster

feat: give maintainers access to the EKS cluster TDE-926

---

infra/eks/cluster.ts

```
➜ aws eks update-kubeconfig --name Workflows --region ap-southeast-2
An error occurred (AccessDeniedException) when calling the DescribeCluster operation: User: arn:aws:sts::019359803926:assumed-role/WorkflowMaintainerRole/RClarke@linz.govt.nz is not authorized to perform: eks:DescribeCluster on resource: arn:aws:eks:ap-southeast-2:019359803926:cluster/Workflows
```
Add the missing policy

fix: maintainers can't describe the cluster TDE-926

---

.github/workflows/main.yml

Sometimes `cdk deploy` asks for approval confirmation. Because using `cdk deploy` part of the CI is not possible to interact with it, we need to bypass this approval.
```
Deployment failed: Error: "--require-approval" is enabled and stack includes security-sensitive updates, but terminal (TTY) is not attached so we are unable to get a confirmation from the user
```
Using `--require-approval never` will bypass the confirmation.

ci: CDK cannot ask for deploy approval without terminal TDE-926

---

docs/infrastructure/components/argo.workflows.md
docs/infrastructure/initial.deployment.md
infra/cdk.ts
infra/cdk8s.ts
infra/charts/argo.workflows.ts
infra/constants.ts
infra/eks/cluster.ts
infra/util/ssm.ts

The aim of this change is to enable the Archived Workflows in Argo so that older workflow runs can be referenced in the future e.g. to see what was run when, what parameters were used.
This change provisions an AWS RDS PostgreSQL database and configures Argo Workflows to use it, so that the Archived Workflows feature is enabled.
- [N/A] Tests updated

feat: Argo Workflows archive feature using RDS TDE-731

---

workflows/basemaps/vector-etl.yaml

Basemaps vector ETL doesnt need the github ssh keys anymore and have been deleted from the cluster, since this workflow still references it, it will no longer start.
Removes the missing secret references and improves the readability of the workflow yaml

fix: correct github secrets access for basemaps etl

---

infra/cdk8s.ts

All pushes to GitHub will now use the same PAT from user `linz-li-bot`, updating the secret names to reflect this.
Rename the GitHub secret generated from `github-linz-basemaps-pat` to `github-linz-li-bot-pat`. This will be deployed as a new secret. The old secret will be removed once the workflows have been updated (separate PR to follow).

fix: update secret name to linz-li-bot-pat TDE-940

---

workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/imagery-import.yaml
workflows/raster/README.md
workflows/raster/ascii-standardise-publish.yaml
workflows/raster/publish-copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising-publish-import.yaml
workflows/raster/standardising.yaml

The region of the dataset is a useful information to be able to filter on.
`region` is passed as a parameter of the workflow to the `linz.govt.nz/region` label value. This is a mandatory field proposed as an enum to the user. Any modification of the `region` list will have to be applied at all the places it is used.
This change is also part of TDE-955 that will use this workflow parameter as an input of a task/step to build the dataset title.

feat: add region label to imagery related workflows TDE-957, TDE-955

---

workflows/raster/publish-copy.yaml

The publish-copy script does not have permission to write to the `linz-topographic` or `linz-elevation` buckets.
Add in the write config paths for these buckets.

fix: add write config to publish-copy workflow for elevation and topographic buckets

---

workflows/raster/README.md
workflows/raster/publish-copy.yaml
workflows/raster/publish-odr.yaml

the linting steps were not working as expected for the imagery team:
- even when linting fails the copy still occurs as the `depends: lint-inputs` step is missing
- preference to default lint to false in publish-copy
- preference to not specify in publish-odr - use nz-imagery bucket name to determine if should lint
_publish-copy_
- `lint` now defaults to `false`
- Only copies/continues if lint-inputs succeeds or is skipped 
_publish-odr_
- remove `lint` parameter
- only lints if target bucket = nz-imagery
- Only copies if lint-inputs succeeds or is skipped

fix: add missing depends arguments TDE-987

---

workflows/raster/publish-odr.yaml

Currently publish odr is not deploying in the github actions due to:
```
error: error parsing workflows/raster/publish-odr.yaml: error converting YAML to JSON: yaml: line 99: did not find expected key
Error: Process completed with exit code 1.
```
For example: https://github.com/linz/topo-workflows/actions/runs/7241106148/job/19724840294
upon investigation ' needs to be changed to " in when statement 

fix: parsing error

---

docs/infrastructure/components/fluentbit.md

We are seeing some errors in the Fluent Bit pods logs that are not harmful as the logs a finally get sent to CloudWatch.
Adding information about this error logs to inform the cluster maintainer if it needs to be ignored or investigated further. 

docs: troubleshooting Fluent Bit broken connection TDE-994

---

workflows/raster/standardising.yaml

We may reprocess imagery in the future so we should keep all licensors that have been used.
See https://linz.slack.com/archives/C01BWPHA1EU/p1703040633399969

fix: reinstate Sinergise as a licensor

---

docs/infrastructure/components/fluentbit.md
infra/charts/fluentbit.ts

Due to some managed network issues dealt by Fluent Bit application pods, the amount of logs increased dramatically which has a considerable impact on our cloud storage cost. A solution (that could be temporary until this network errors stop/slow down if we find a way to fix them?) is to stop sending the Fluent Bit application pod logs to CloudWatch.
Telling Fluent Bit to ignore its own logs using the [exclude annotation](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#request-to-exclude-logs).
Consequences are that these logs won't be shipped through our system (not being seen in Elasticsearch). We are still able to view them from the EKS Cluster that we have hands on.

feat: do not send Fluent Bit application logs to CloudWatch TDE-1016

---

docs/infrastructure/components/fluentbit.md
infra/charts/argo.workflows.ts

The Argo Controller pod are having this issue https://github.com/argoproj/argo-workflows/issues/11657. This issue is increasing our storage log cost.
Excluding the controller pods so Fluent Bit is not sending their logs to CloudWatch.
Extract of the Deployment with the change:
```
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app.kubernetes.io/component: workflow-controller
app.kubernetes.io/instance: argo-workflows
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: argo-workflows-workflow-controller
app.kubernetes.io/part-of: argo-workflows
app.kubernetes.io/version: v3.4.11
helm.sh/chart: argo-workflows-0.34.0
linz.govt.nz/build-id: ""
linz.govt.nz/git-hash: 628900c56465bd942d68dac4f29faa35c9667b48
linz.govt.nz/git-repository: linz__topo-workflows …
```

fix: temporary stop sending Argo controller logs TDE-1016

---

workflows/basemaps/imagery-import-cogify.yml

Create covering using too much memory for both processing and caching. We will remove the caching the future feature, and move the task into spot node to avoid exceed the memory.
Use spot instance for the create-covering task.

feat(basemaps): Move the create covering into spot instance to avoid exceeding memory

---

workflows/basemaps/imagery-import-cogify.yml

We need to downgrade the create-overview to basemaps cli v6. As this is currently removed in v7 when we doing upgrade of AWS CDK and chunkd in [basemaps](https://github.com/linz/basemaps/commit/6b6e409553b74a10b7c79b077c1a89797747d5d3). 
So we will fix the create-overview task to cli v6 for now until we got a new one in the basemaps cogify in future.
Fix the basemaps cli version to v6 for the create-overview tasks.

feat(basemaps): Downgrade to the create-overview tasks to v6.

---

workflows/raster/publish-odr.yaml

The ODR bucket should not contain TFW files. The TFW files are sometimes provided by the data supplier (also sometimes other sidecar files like `.proj`). We use these sidecar files to get extra information while standardising the data, but would not want to distribute them with the standardised data: all datasets don't have them.
Remove the TFW files from the `include` parameter default value.
The existing data should not be impacted, as the standardised files folder (`flat/` directory) was not including any other files than `tiff` and `json`.

fix: publish-odr should not copy TFW files

---

workflows/raster/standardising.yaml

Align `topo-imagery` [categories](https://github.com/linz/topo-imagery/blob/cde875dc730011165b73848338a700394eccdb4b/scripts/stac/imagery/metadata_constants.py#L40)
`Scanned Aerial Imagery` -> `Scanned Aerial Photos`

fix: scanned aerial imagery does not exist in topo-imagery TDE-955

---

templates/argo-tasks/create-manifest.yml

fixes a bug where workflows which run `create-manifest` would fail with an `^ Unknown arguments` message.
- `group_size` reverted to `group-size`
- `copy-option` changed to `copy_option` for consistency - although the copy option parameter is never used here?
~~- [ ] Tests updated~~ no tests but tested in argo
~~- [ ] Docs updated~~ not required docs are correct

fix: invalid underscore for create-manifest group-size parameter TDE-959

---

workflows/raster/publish-copy.yaml
workflows/raster/publish-odr.yaml

Align the `publish-copy` and `publish-odr` workflowtemplates with the downstream sub-templates.
Replace `aws-role-config-path` with `aws_role_config_path`

fix: publish-copy parameter hyphens TDE-826

---

workflows/raster/standardising.yaml

AAM NZ now operates as Woolpert.

feat: add new producer to imagery standardise workflow

---

workflows/raster/ascii-standardise-publish.yaml
workflows/raster/publish-copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising-publish-import.yaml
workflows/raster/standardising.yaml
workflows/stac/stac-validate.yaml
workflows/util/create-thumbnails.yaml

Bump the container version of argo-tasks (and a few of topo-imagery) to use [new features](https://github.com/linz/argo-tasks/releases/tag/v3.0.0).
Update container version.

chore: update container versions TDE-961 TDE-1014

---

templates/argo-tasks/README.md
templates/argo-tasks/create-manifest.yml
workflows/raster/README.md
workflows/raster/ascii-standardise-publish.yaml
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising-publish-import.yaml
workflows/test/flatten.yaml

To prevent copy of the `.geojson` footprint files.
Escape the `.` in the `.json$` in the regex so we don't copy all `.geojson` files that get matched.
N/A

fix: create-manifest copy regex needs to match full stop

---

templates/argo-tasks/copy.yml
templates/argo-tasks/create-manifest.yml
templates/argo-tasks/generate-path.yml
templates/argo-tasks/group.yml
templates/argo-tasks/push-to-github.yml
templates/argo-tasks/tile-index-validate.yml

Bring the templates into line with the workflows and workflowtemplates to be consistent. It should have no functional effect as the upstream workflows specify Argo Tasks `v3` which will override the templates, but there is always the possibility that this might not be specified upstream.
Change `version_argo_tasks` to `v3` in templates.

chore: update templates with Argo Tasks v3

---

workflows/raster/README.md
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising-publish-import.yaml

The previous regex looked for a match for the start of the filename i.e. `^capture-area.geojson$`, however, when running on Argo Workflows, the path given when matching is always the full S3 object (path), so this did not match.
Change `^` to `/` to match the full filename. Also escape the full stop to look for a literal full stop character.
N/A workflow bug

fix: regex for matching capture-area.geojson

---

templates/README.md
workflows/tiv.yml

These topographic upload links will remain lowercase

revert: replace all error in documentation (SKYVUW/SKYCAN) TDE-1033

---

workflows/raster/standardising.yaml

A direct access to the `capture-area.geojson` file from the workflow UI can be useful for the user to verify data. https://github.com/linz/topo-imagery/pull/860
Add a workflow artifact containing the local copy of `capture-area.geojson`

feat: expose capture-area.geojson TDE-1045

---

workflows/raster/README.md
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/test/generate-path.yaml

Enable publish-odr to also push to linz/elevation 
**publish-odr:**
- Will always use a generated-target-path
- Will always publish to github
- Can publish to linz/imagery or linz/elevation
_nb: I will create a separate PR with a workflow that can be run in the event someone needs to publish to the odr and specifiy the target rather than automatically generating it (a backup workaround for any difficult datasets)_
**Copy**
- Will always require a target path (can use test-generate-path to build target)
- Will never publish to github
- Cannot publish to ODR
**test-generate-path**
New test workflow template for use to check the generated target path (superceding: https://github.com/linz/argo-tasks/blob/docs/tmp-generate-path/src/commands/path/TMP_DOC.md) 
_If not applicable, provide …

feat: enable publish to elevation TDE-1037

---

workflows/raster/publish-odr.yaml

bug in production
`create-manifest` should be `create-manifest-github`

fix: create-manifest should be create-manifest-github

---

workflows/raster/standardising.yaml

The create-collection standardising workflow step has changed to also create the `capture-area.geojson` file, which is a more computationally intensive task and can take a long time.
Change the CPU from `2000m` to `15000m`.

fix: allocate more CPU resources to the create-collection workflow task TDE-988

---

infra/charts/kube-system.coredns.ts

Our logs get forwarded out of EKS into cloudwatch then into elastic search, by logging every DNS query we are adding a lot of strain on the logging process.
Disable DNS query logs.

fix(infra): disable coredns logs as it is too spammy TDE-1064

---

infra/eks/cluster.ts

Argo Workflows needs read access to the public ODR buckets in order to achieve tasks that needs reading published files such as [`stac-validate`](https://github.com/linz/topo-workflows/tree/master/workflows/stac).
Grant read access to `s3://nz-elevation` and `s3://nz-imagery` to the Argo Runner service account.
**The change has been deployed and tested on `nz-imagery` with [a `stac-validate` workflow](https://argo.linzaccess.com/workflows/argo/stac-validate-8l4qv?tab=workflow).**

feat: give Argo Workflows read access to ODR buckets TDE-1065

---

workflows/raster/standardising.yaml

https://github.com/linz/topo-imagery/pull/891 needs `--gsd` to be passed to standardise_validate script.
Pass the existing gsd parameter to standardise-validate step
**It needs a https://github.com/linz/topo-imagery/pull/897 release.**

feat: pass gsd to standardise-validate TDE-1080

---

infra/charts/kube-system.coredns.ts

We are investigating some DNS related issues, would be nice to see the logs of DNS queries so we can have more information.
This reverts commit 942f297df9609d68a08d86bcd9b1017394d0088a.

fix: revert "fix(infra): disable coredns logs as it is too spammy TDE-1064 (#472)" TDE-1084

---

workflows/raster/standardising.yaml

Saving the Basemaps config URL in the s3 target path (flat directory) will allow another workflow to grab its value.
Save an artifact config-url containing the basemaps config url in s3

feat: save basemaps config url as artifact in s3 TDE-1098

---

workflows/raster/README.md
workflows/raster/ascii-standardise-publish.yaml

update ascii-standardising workflow so that it is ready to publish elevation data
update the workflow to use:
- argo-tasks v3
- topo-imagery v4 **nb: this version of topo-imagery makes the translate-ascii step quite slow I will investigate this however this PR will work**
- publish-odr 

fix: update elevation ascii workflow TDE-1050

---

templates/argo-tasks/README.md
templates/argo-tasks/generate-path.yml
templates/argo-tasks/push-to-github.yml
workflows/raster/README.md
workflows/raster/publish-odr.yaml

Provide more info for imagery and elevation PR reviews and copy the item TIFFs and STAC files only after the PR is approved and merged.
The ticket and copy-option need to be part of the Pull Request.
The `create-manifest` and `copy` tasks are removed from the `publish-odr` workflowtemplate.
The `publish-to-github` workflowtemplate is updated for the new fields in Argo Tasks that are to be passed through to the Pull Request.

feat: update publish-odr to remove copy and add new PR fields TDE-1100 TDE-1102

---

workflows/raster/README.md

Very minor change to update the raster workflows README in line with the `publish-odr` workflow.

docs: remove default bucket name from publish-odr README

---

workflows/raster/copy.yaml

Make the `create-manifest` step have consistent inputs.
Add `target` as an input to `create-manifest` in the same way as `source`.

fix: input parameters for consistency in copy create-manifest step

---

infra/charts/argo.workflows.ts

In order to reduce the Argo controller logs due to [this issue](https://github.com/argoproj/argo-workflows/issues/11657), we can use [this workaround](https://github.com/argoproj/argo-workflows/pull/12622) for now.
Using `WATCH_CONFIGMAPS=false` workaround implies upgrading Argo Workflows:
- upgrade Argo Workflows to `3.5.5`
- set `WATCH_CONFIGMAPS` to Argo Controller environment variable to `false`
Non regression tested on a NonProd cluster.

fix: use WATCH_CONFIGMAPS workaround TDE-1015

---

infra/charts/kube-system.coredns.ts

AWS changed the way to check the readiness of CoreDNS. See https://aws.amazon.com/blogs/containers/recent-changes-to-the-coredns-add-on/ and https://github.com/aws/containers-roadmap/issues/941
Add the ready plugin in the corefile config.

fix: coredns readiness changed from health to ready check

---

infra/charts/fluentbit.ts

Inside kubernetes, DNS resolution uses ndots: 5 this means any dns requests that has less than 5 dots will go through all the search domains before looking up the actual domain. AWS Cloudwatch `logs.ap-southeast-2.amazonaws.com` has 3 dots.
Hardcode the Cloudwatch endpoint  to `logs.ap-southeast-2.amazonaws.com.` so DNS requests to Cloudwatch force the DNS lookup to be fully qualified.
This has been tested on a non prod cluster and we've seen a reduction of the DNS queries to the `coredns`

feat: force fqdn dns request for cloudwatch resolution by fluentbit TDE-1093

---

workflows/basemaps/mapsheet-json.yaml

The national 10m satellite imagery mosaic has had a name change since the source imagery was published to the ODR.
Previously it was named `nz_satellite_2021-2022_10m_RGB` in the basemaps aerial config
It is now named `new-zealand_2022-2023_10m`. This new name structure will continue going forward.

feat: change default value for exclude argument

---

workflows/basemaps/vector-etl.yaml
workflows/cron/cron-vector-etl-roads-addressing.yaml

Another cron etl workflow for update the [53382-nz-roads-addressing](https://data.linz.govt.nz/layer/53382-nz-roads-addressing/) data.
- Add new cron workflow running 6am Wednesday for update nz road addressing vector data.
- Upgrade the argo task to v3 to support individual vector tileset in create-pr.

feat(basemaps): Cron workflow for update nz roads addressing vector layer. BM-977

---

infra/charts/argo.workflows.ts

https://github.com/linz/topo-workflows/pull/498 has been using the wrong environment variable name to disable watching configmaps, so the issue is not fixed.
Use the correct [environment variable name](https://argo-workflows.readthedocs.io/en/stable/environment-variables/)

fix: argo controller disabling watch configmap wrong env var name TDE-1016

---

infra/charts/kube-system.node.local.dns.ts

Our analytics use the container name for DNS query logs, `node-cache` is not easily mappable to `node-local-dns`
Switches the container name of node-local-dns to "node-local-dns" 

fix: rename node-cache to node-local-dns

---

workflows/cron/cron-vector-etl-roads-addressing.yaml
workflows/cron/cron-vector-etl.yaml

Parameter name is defined incorrectly in the cron workflow.
fix the name in two cron workflow

fix(cron): Add the missing parameter name for the cron workflow

---

docs/retry.md
infra/charts/argo.workflows.ts
templates/argo-tasks/copy.yml
templates/argo-tasks/push-to-github.yml
workflows/basemaps/create-config.yaml
workflows/basemaps/create-overview-all.yaml
workflows/basemaps/create-overview.yaml
workflows/basemaps/imagery-import-cogify.yml
workflows/raster/standardising.yaml
workflows/stac/stac-validate.yaml
workflows/test/flatten.yaml
workflows/util/create-thumbnails.yaml

We want every task within our workflows to retry (twice) automatically and on a different node/host (network issues) when they fail.
Configure the `retryStrategy` at the `workflowDefaults` level.
Notes: 
- the `nodeAntiAffinity` to prioritize retrying on a different node/host is not working due to an issue in the Argo Workflows system. A [PR is opened](https://github.com/argoproj/argo-workflows/pull/12701) in the Argo repo
- this change will make every task retrying on failure. Some of our tasks (for example, `stac-validate`, `tileindex-validate`) are expected to fail if the system invalidate something. They will still retry twice in that case. This would be handle in a separate PR.

feat: default retryStrategy TDE-1112

---

templates/argo-tasks/copy.yml
templates/argo-tasks/create-manifest.yml
templates/argo-tasks/generate-path.yml
templates/argo-tasks/group.yml
templates/argo-tasks/push-to-github.yml
templates/argo-tasks/tile-index-validate.yml
workflows/basemaps/create-config.yaml
workflows/basemaps/create-overview-all.yaml
workflows/basemaps/create-overview.yaml
workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/mapsheet-json.yaml
workflows/basemaps/vector-etl.yaml
workflows/cron/cron-vector-etl-roads-addressing.yaml
workflows/cron/cron-vector-etl.yaml
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising.yaml
workflows/raster/tests.yaml
workflows/stac/stac-validate.yaml
workflows/test/env.yaml
workflows/test/flatten.yaml
workflows/test/generate-path.yaml
workflows/test/list.arm.yaml
workflows/test/list.yaml
workflows/test/sleep.yml
workflows/util/create-thumbnails.yaml

The jsonschema version should be consistent with the Argo version deployed.
Upgrade jsonschema version as the yaml-language-server of the workflow files.

chore: upgrade argo jsonschema to 3.5.5

---

.github/workflows/main.yml

[This change](https://github.com/linz/topo-workflows/pull/520) introduced the fact that Argo Workflow Controller is not picking up changes in ConfigMap, [as specified for the added `WATCH_CONTROLLER_SEMAPHORE_CONFIGMAPS` environment variable](https://argo-workflows.readthedocs.io/en/stable/environment-variables/#controller).
An initial test showed that the `semaphore` changes were picked up, but, unfortunately, no further test on the controller ConfigMap has been done.
The workaround is to restart the controller at each kubernetes config deployment to make sure changes are picked up. This does not cause downtime.

fix: workflow-controller is not picking up ConfigMap changes TDE-1016 TDE-1112

---

workflows/basemaps/create-config.yaml
workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/mapsheet-json.yaml
workflows/basemaps/vector-etl.yaml
workflows/cron/cron-vector-etl-roads-addressing.yaml
workflows/cron/cron-vector-etl.yaml
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising.yaml
workflows/stac/stac-validate.yaml
workflows/test/flatten.yaml
workflows/test/generate-path.yaml
workflows/util/create-thumbnails.yaml

The `metadata.namespace` is overriden when the WorkflowTemplates and CronWorkflows are deployed (using `--namespace`).
Having this data is redundant but also create issue while linting locally (`argo lint --offline`) the WorkflowTemplates with `templateRefs` when namespaces do not match.
Remove the default namespace in `metadata.namespace` from all WorkflowTemplate and CronWorkflow files

refactor: remove metadata.namespace from WorkflowTemplates and CronWorkflows TDE-1149

---

workflows/raster/publish-odr.yaml
workflows/raster/standardising.yaml

An enum default value should be one of the enum values. `argo lint` fails on this.
Add the default value in the enum values.

fix: WorkflowTemplates linting fails TDE-1143 TDE-1149

---

infra/cdk.ts
infra/charts/argo.workflows.ts
infra/charts/fluentbit.ts
infra/constants.ts

It is easier to maintain the region of our AWS stack if we have to modify it in a single place.
Store the region in a constant.

refactor: store default region in const

---

.github/workflows/main.yml

The current process of linting the workflows is complex as we need to publish them on the kubernetes cluster. Using an offline mode makes things simpler and quicker, removing the connection to the cluster.
Use the `--offline` mode to run `argo lint`, rather than linting from the resources deployed on the cluster.

ci: use --offline mode to lint workflows TDE-1149 TDE-1143

---

workflows/raster/README.md
workflows/raster/standardising.yaml

Enable the Basemaps configuration for `dem_lerc`, as Basemaps now supports previewing Elevation data.
Remove exclusion for `dem_lerc` preset.

fix: enable Basemaps preview for Elevation data TDE-1151 BM-932

---

templates/argo-tasks/README.md
templates/argo-tasks/stac-validate.yml
workflows/raster/publish-odr.yaml
workflows/raster/standardising.yaml
workflows/stac/README.md
workflows/stac/stac-validate-parallel.yaml

`stac-validate` is used in many places, it should be easier to maintain and reuse if it was a "template".
Create a `stac-validate` template so it can be re-use by workflows

refactor: templating stac-validate workflow TDE-1136

---

infra/charts/argo.workflows.ts

We've noticed that karpenter is erroring since https://github.com/linz/topo-workflows/pull/506. Errors makes us thinking that it could be related. Since the retry on a new node using `nodeAntiAffinity` [is not working](https://github.com/argoproj/argo-workflows/pull/12701), it's a good idea to remove it to see if it solved `karpenter` issues.
Remove the `affinity` in the `retryStrategy`.

fix: node nodeAntiAffinity seems to break karpenter TDE-1112 BM-1018

---

templates/argo-tasks/tile-index-validate.yml
workflows/raster/README.md
workflows/raster/standardising.yaml

We only want to check `webp` datasets are 8-bit so Argo Tasks tileindex-validate needs to know the dataset type.
Pass the `compression` type of the dataset to Argo Tasks tileindex-validate as `preset` for validation

fix: pass compression as preset to tileindex-validate TDE-895 TDE-1151

---

templates/argo-tasks/tile-index-validate.yml

Mistake in parameter name, renamed to `preset`

fix: preset parameter name TDE-895 TDE-1151

---

workflows/basemaps/create-config.yaml
workflows/raster/standardising.yaml

Basemaps need to be on v7+ for DEM support
Upgrades basmeaps cli from v6 to v7
Locks create-overview to v6 until overview creation is redone in v7 BM-944

build: upgrade basemaps cli to v7 for DEM support BM-932

---

workflows/basemaps/imagery-import-cogify.yml

It is helpful to have all pull requests linked to the ticket, since we now have the ticket number in the workflow we should pass it into anything interacting with github
Adds ticket number to basemaps `create-pr` action.
This pull request needs https://github.com/linz/argo-tasks/pull/962 to be merged first.

feat: include ticket number in basemaps pull requests TDE-1146

---

templates/argo-tasks/README.md
templates/argo-tasks/stac-validate.yml
workflows/stac/stac-validate-parallel.yaml

`stac-validate` has changed its flags for checksum validation in https://github.com/linz/argo-tasks/pull/982 & https://github.com/linz/argo-tasks/pull/972
Use the `--checksum-assets` and `--checksum-links` flags

feat: stac-validate workflows use specific checksum flags TDE-1134

---

workflows/raster/standardising.yaml

NIWE Lidar contracted by Regional Software Holdings Limited (RSHL)
Add RSHL as a licensor

feat: add RSHL as a licensor

---

workflows/stac/stac-validate-parallel.yaml

In the case of a task in `tpl-at-stac-validate` fails more than twice and the workflow came back failing, the entire `stac-validate-collections` is retried twice which cause to run the inner stac-validate workflow.
Avoid tasks in the `stac-validate-parallel` workflow to retry by default.
Force `aws-list-collections` to retry twice if it fails.
This is a work around as I could not find a way to specify the retryStrategy at a task level using a `templateRef`

fix: stac-validate-collections retries should be managed by tpl-at-stac-validate only TDE-1178

---

workflows/raster/standardising.yaml
workflows/raster/tests.yaml
workflows/test/env.yaml
workflows/util/create-thumbnails.yaml

We use the Docker `ENTRYPOINT` (Argo `command`) to activate the virtualenv before running Python. We've [verified that this change is backwards compatible by running it with topo-imagery v4.7.1](https://argo.linzaccess.com/workflows/argo/test-is-docker-args-w9p88?tab=workflow&nodeId=test-is-docker-args-w9p88-2719834120&nodePanelView=containers&uid=e8af157e-77c5-403c-bbaa-12525efdf7db).
Use `args` rather than `command` for specifying the interpreter and file to run.

fix: Don't override topo-imagery Docker entrypoint for Python TDE-1179

---

.github/workflows/main.yml
.github/workflows/pull-request.yml
package-lock.json
package.json

Support current LTS release.
1. Update the engine:
```
jq '.engines.node = "^20.13.1"' package.json | sponge package.json
```
2. Update the lock file:
```
npm install
```
3. Update the uses of `linz/action-typescript`:
```
for path in .github/workflows/*.y*ml; do
yq --inplace '(.jobs.*.steps[] | select(.uses == "linz/action-typescript*").with.node-version) = "20.x"' "$path";
done
```

build: Bump Node.js to latest LTS, 20.13.1 TDE-1090

---

infra/charts/karpenter.ts

Karpenter should allow on-demand instances.
Add `on-demand` in the list of requirements capacity types.

feat: karpenter allows on-demand instances TDE-1185

---

infra/charts/karpenter.ts
workflows/test/sleep.yml

We would prefer only short term jobs from argo are run on large nodes that are created by karpenter
taint all provisoners that karpenter has so pods have to opt into being created by karpenter.

fix: ensure only argo jobs are run on nodes created by karpenter TDE-1185

---

workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/vector-etl.yaml
workflows/cron/cron-vector-etl-roads-addressing.yaml

We are adding new config type for elevation data which leads to three types of configs in Basemaps. So [pull request](https://github.com/linz/argo-tasks/pull/953) will need to select which config type that is needed for the imported imagery.
This is blocking by argo-tasks release. Not ready yet. Sorry to make this as non draft PR, accidentally pushed enter when editing.

feat(basemaps): Support elevation config for the config import. BM-936

---

workflows/cron/cron-stac-validate-fast.yaml
workflows/cron/cron-stac-validate-full.yaml

The STAC validation cron job fast workflow was not checking link checksums due to a duplication of a workflow parameter template variable.
Correct copy and paste error in the STAC validation cron job workflows.

fix: stac-validate cron job argument parameters TDE-1214

---

workflows/basemaps/create-config.yaml
workflows/basemaps/imagery-import-cogify.yml
workflows/raster/standardising.yaml

Cogify commands was using the .bin/cogify which require dev dependencies to be installed as well. We can just use the index.cjs instead.
This will required https://github.com/linz/basemaps/commit/6610322a12b89c20060346b24763c62e0225e3bf to be released
Call cogify from `/app/node_modules/.bin/cogify` to `/app/node_modules/@basemaps/cogify/dist/index.cjs`

fix(basemaps): Using dist/index.cjs for cogify commands.

---

workflows/raster/standardising.yaml

If the standardising workflow fails, the entire workflow is retried twice, even the pods that succeeded. We only want the failed pods to retry.
Specify no retries on the main template level, allowing the default retry of 2 to remain on the individual steps.
Behaviour before this change:
Behaviour after this change:

fix: retry only failed pods on standardising workflow TDE-1216

---

workflows/basemaps/imagery-import-cogify.yml

When importing imagery into basemaps sometimes URLs are misstyped and import the wrong colleciton of imagery, by requiring a collection.json to be present at the root of the imagery we can reducee the chance of incorrect imagery being imported.
_Why is this change being made? What implications or other considerations are there?_
Adds "--require-stac-collection" flag to the basemaps import process which is defaulted to true.

feat: require a stac collection.json when importing into basemaps BM-1047

---

infra/charts/fluentbit.ts

We're not seeing some logs propagated from Argo Workflows workflow pods to Elasticsearch.
This issue and a solution can be found here: https://github.com/argoproj/argo-workflows/issues/13314. 
Increase the [Fluent Bit Kubernetes Filter `Buffer_Size`](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#configuration-parameters) from its default `32k` to `128k` as it seems to solve our problem.
If we experience this issue again, it could not be enough and we'll proceed to another increase in time.

fix: increase Fluent Bit Kubernetes Filter Buffer_Size to 128k TDE-1232

---

templates/common/README.md
templates/common/exit.handler.yaml
workflows/raster/standardising.yaml

The Argo Workflows workflows parameters are not logged in our log discovery system. The workflows status is handled by Kubernetes Event Exporter.
Having a log that record the workflow status and its parameter on the `onExit` event is helpful to implement more specific alerting.
- Add a `tpl-exit-handler` workflowTemplate that create a log containing the workflow status and parameters. For example:
``` json
{"time":1722568553969,"level":20,"pid":1,"msg":"Workflow:Succeeded","version_argo_tasks":"v4","version_basemaps_cli":"v7","version_topo_imagery":"v4","ticket":"","region":"new-zealand","source":"s3://linz-imagery-staging/test/sample/","include":".tiff?$","scale":"500","validate":"false","retile":"false","source_epsg":"2193","target_epsg":"2193","group":"50","compression":"webp","create_c …
```

feat: log imagery-standardising workflow information onExit TDE-1230

---

workflows/raster/standardising.yaml

As `tpl-exit-handler` template already retries its own task, we don't need the caller template to retry it if there is a failure.
- limit the retry of the entire `tpl-exit-handler` template to 0 when called from `standardising` workflow

fix: exit-handler template already retries TDE-1230

---

infra/charts/argo.workflows.ts
workflows/README.md
workflows/basemaps/create-config.yaml
workflows/basemaps/create-overview-all.yaml
workflows/basemaps/create-overview.yaml
workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/mapsheet-json.yaml
workflows/basemaps/vector-etl.yaml
workflows/cron/cron-stac-validate-fast.yaml
workflows/cron/cron-stac-validate-full.yaml
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/stac/stac-validate-parallel.yaml

With the current default `retryStrategy`, all templates are retried with the limit put in place. When a pod withing a workflow reach its retry limit without any success, the entrypoint template (`main`) of the workflow is also retried using this `retryStrategy`. It is not efficient as at that point the entire workflow is retried (and the failing template/pod as well!).
- avoid the retry on entrypoint template for the workflows in `workflows/`, not the `workflowTemplate` in `templates` as they have only one template which is also their entrypoint.
- move the default `retryStrategy` to `templateDefaults` as it is there that it belongs. This did not change the behaviour from the test I ran.

fix: entire workflow should not retry TDE-1236

---

infra/charts/argo.workflows.ts

When a task fails because a pod get deleted (not linked to an application error), the task is not retried.
- set the `retryPolicy` to `OnError` so the task get retried if a pod is deleted. See: https://argo-workflows.readthedocs.io/en/latest/tolerating-pod-deletion/#tolerating-pod-deletion

fix: task should retry when pod get deleted TDE-1241

---

workflows/basemaps/vector-etl.yaml

The new ETL got a cli for `check-updates`, which will return the layers that require to updated and process.
Add this feature into ETL workflow that can skip running if there is no updates.
Before merging we need to do a ETL releases. https://github.com/linz/basemaps-team/pull/828

feat(basemaps): Skip running ETL if there is no updates. BM-1056

---

workflows/basemaps/vector-etl.yaml

Seems `create-pr` still running when etl skipped. So we might need add the `requiredUpdate` check to `create-pr` condition as well.
_Why is this change being made? What implications or other considerations are there?_

fix(basemaps): Stop running create pr if no etl update required.

---

workflows/basemaps/create-config.yaml
workflows/basemaps/create-overview-all.yaml
workflows/basemaps/create-overview.yaml
workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/mapsheet-json.yaml
workflows/basemaps/vector-etl.yaml
workflows/cron/cron-stac-validate-fast.yaml
workflows/cron/cron-stac-validate-full.yaml
workflows/cron/cron-vector-etl-roads-addressing.yaml
workflows/cron/cron-vector-etl.yaml
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising.yaml
workflows/raster/tests.yaml
workflows/stac/stac-validate-parallel.yaml
workflows/test/env.yaml
workflows/test/flatten.yaml
workflows/test/generate-path.yaml
workflows/test/list.arm.yaml
workflows/test/list.yaml
workflows/test/sleep.yml

Managing pod labels helps to do some kind of filtering/analytics on the pod runs and improve logging information.
- populates the pod labels using `podMetadata` at the workflow spec level. Workflow `templates` that are called, get their pods to get these labels too.

feat: add labels at the podMetadata level TDE-1249

---

.eslintrc.cjs
package.json
templates/common/__test__/exit.handler.test.mjs
templates/common/__test__/exit.handler.test.ts
tsconfig.json

Bring a test for the inner script in the exit-handler workflowTemplate.
- add a function that grab the script content of the exit handler template to test it
- modify the npm test script to target this new test file

test: test exit-handler template script TDE-1230

---

workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/vector-etl.yaml
workflows/cron/cron-stac-validate-fast.yaml
workflows/cron/cron-stac-validate-full.yaml
workflows/raster/copy.yaml
workflows/raster/publish-odr.yaml

The exit handler logs some useful information about a workflow when it's done. These can be helpful for logging and alerting.
- call exit-handler task `onExit`

feat: add exit handler tasks TDE-1230

---

workflows/raster/standardising.yaml

Large standardizing jobs need more than 3Gi of storage, the nodes are allocated 200Gi of storage so we need a number that somewhat divides from 200Gi but not exactly so prefer 19.8Gi over 20Gi
Up the diskspace allocation to 29.5Gi per pod from 3Gi

fix: increase storage of standardising pods to prevent out of diskspace errors TDE-1271

---

workflows/raster/standardising.yaml

Dates are pulled from Items: https://github.com/linz/topo-imagery/pull/1099
- remove start and end date parameters from create-collection
- bump topo-imagery version

refactor: create-collection does not use dates anymore TDE-1258

---

docs/infrastructure/kubernetes.version.md

This way it's easier to run the process without any typos.
Use a variable rather than static values for the node group name.

docs: Use a variable for the node group name TDE-1255

---

templates/argo-tasks/README.md
templates/argo-tasks/generate-path.yml

Allowing the generate-path template to use the new flag available https://github.com/linz/argo-tasks/pull/1067
add a new parameter to handle the flag

feat: --no_date_in_survey_path handling TDE-1261

---

templates/argo-tasks/README.md
templates/argo-tasks/generate-path.yml

see https://github.com/linz/argo-tasks/pull/1104
- `no_date_in_survey_path` --> `add_date_in_survey_path`

fix: avoid double negative arguments TDE-1261

---

docs/infrastructure/gde-argo-runbook.md

Create a disaster recovery Runbook for restoring Argo Workflows with EKS and RDS so that the cluster can be rebuilt easily.
Moved from https://github.com/linz/topo-aws-infrastructure/pull/366 - should address all the issues brought up there.

docs: GDE Argo disaster recovery runbook TDE-1281

---

.github/workflows/main.yml

Verify that upgrades to infrastructure don't break anything obvious.
Run a smoke test when deploying to production
Tests:
- [Successful run](https://github.com/linz/topo-workflows/actions/runs/11374906512/job/31644537379?pr=818)
- [Forced failing run](https://github.com/linz/topo-workflows/actions/runs/11375004840/job/31644827064?pr=818) because of `--parameter=validate=true`

test: Run imagery standardising smoke test on infra changes TDE-1285

---

.github/workflows/main.yml

If a `md` file is modified, the CI process should not deployed the infrastructure as there is no change.
- exclude `md` files from the `git diff`

ci: exclude md files when determining if infra changed

---

workflows/raster/copy.yaml

`value` sounds more appropriate to use for the WorkflowTemplate parameter values we want to default for the users.
- `flatten` workflow parameter default value is now stored in `value` rather than `default`
Note on `default` vs `value`:
From my understanding, `default` would used if no `value` is  supplied. In the case of a user of the WorkflowTemplate and at a `arguments.parameters` level, using `value` seems more appropriate.
Using `default` and `value` would be appropriate in the following example:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
name: my-wft
entrypoint: main
arguments:
parameters:
- name: my_param
value: ''
templates:
- name: main
dag:
tasks:
- name: my-task
templateRef:
name: my-tpl
template: main
arguments:
parameters:
- name: my_param
value: …
```

fix: use value instead of default in copy wf TDE-1323

---

templates/argo-tasks/stac-setup.yml

`geographic_description` will not be supplied for all datasets e.g. the National DEM.

fix: set default geographic_description for stac-setup TDE-1318

---

workflows/raster/standardising.yaml

The key output by get-location does not end with a trailing `/`. The create-config task should manage the path within the bucket correctly.
Add a `/` between the key and the `flat` in the artifact path for the config-url.

fix: create config url should be stored in /flat TDE-1321

---

workflows/raster/standardising.yaml

When creating a Collection from the imagery-standardising workflow, the created and updated date should remains the same as for the Items, using a constant rather than the system execution time.
- Use the same datetime that is used for the Items

fix: Collection created updated should be the workflow run datetime TDE-1341

---

workflows/raster/standardising.yaml

When a dataset is resupplied (the dataset already exist / is already published), the Collection should keep track of the updates. In order to do that, the `created` datetime should remains the one that have been introduced at the initial creation/publication of the dataset.
- pass the `odr_url` to the `collection_from_items.py` script in the `create-collection` task, so the system retrieve the published Collection to keep its information.

fix: resupplied Collection should keep its created datetime TDE-1340

---

workflows/raster/standardising.yaml

The description of the `copy_option` parameter is missing information about the `--force-no-clobber`.
- update documentation

docs: update description for copy_option parameter

---

infra/charts/fluentbit.ts

The logs are parsed into a `data` field by fluentbit. It is unecessary duplication to keep the `log` field once it has been merged into `data`.
Tells fluentbit to not keep the `log` field once it's parsed into `data`.

fix: remove the log field after its parsed into data field TDE-1337

---

workflows/raster/README.md
workflows/raster/national-dem.yaml

Having a Nationally combined set of DEMs is useful for any data consumer wanted to access to the entire country DEM. This dataset is aimed to be updated on a regular basis to include all new single region/area dataset that is newly published or updated.
Add a WorkflowTemplate that create a nationally combined set of DEM based off a configuration file that list the datasets to include in order of priority. This WF template is able to be used to run a cron workflow.

feat: add a workflowTemplate to create national DEM TDE-1166

---

workflows/cron/README.md
workflows/cron/cron-national-dem.yaml

Making sure that any update made on the 1m DEM datasets (`s3://nz-elevation`) that are listed in [the configuration](https://github.com/linz/basemaps-config/blob/master/config/tileset/elevation.json), or any update in the configuration itself, are propagated to [the whole New Zealand LiDAR 1m DEM dataset](https://github.com/linz/elevation/blob/master/stac/new-zealand/new-zealand/dem_1m/2193/collection.json).
Deploy a CronWorkflow to trigger the `national-dem` workflow against the published [New Zealand LiDAR 1m DEM](https://github.com/linz/elevation/blob/master/stac/new-zealand/new-zealand/dem_1m/2193/collection.json) dataset.
This should be merged after https://github.com/linz/topo-workflows/pull/890

feat: add CronWorkflow to update the national DEM dataset TDE-1162

---

workflows/cron/cron-national-dem.yaml

The cron national dem workflow should not run on weekend to avoid trying to create several PR over the weekend if data has been published on a Friday.
Change the cron schedule

fix: cron national dem should not run on weekends TDE-1162

---

workflows/raster/national-dem.yaml
workflows/raster/standardising.yaml

The `group` field in the `imagery-standardising` workflow was mentioning `standardising` task rather than `standardise-validate`.
Rename task in the description

docs: fix group description

---

.github/workflows/main.yml

prettier is defined in the `package.json` as the formatter for this repository, but it is never run across all files as part of the CI process
Add a prettier `--check` to the formatting step to ensure files are checked for formatting
https://github.com/linz/topo-workflows/actions/runs/12998945699/job/36253186924

build: ensure prettier is run in github actions

---

workflows/cron/cron-national-dem.yaml

The National DEM cron workflow is based on the fact that an existing dataset can be updated without reprocessing the entire dataset (existing files + new files). We don't want to remove this workflow but only suspending it until the updating feature get released.
Suspending it on the deployed cron workflow has the limitation that when a PR get merged to this repo, all the workflows get re-deployed, removing the suspend flag...
Hardcode the suspend flag until the updating feature is released.

feat: suspend national dem cron until the process works TDE-1359

---

templates/argo-tasks/tile-index-validate.yml

Expose new CLI args for `tileindex-validate` from Argo Tasks through the respective workflow
Added input parameter with default value to make this a non-breaking change.

feat: Add includeDerived to tileindex-validate

---

templates/topo-imagery/README.md
templates/topo-imagery/standardise-validate.yaml

Expose new CLI args for standardise_validate.py from topo-imagery in the workflow.
Added `scale_to_resolution` input parameter with default value to make this a non-breaking change.

feat: Add scale_to_resolution to standardise-validate

---

workflows/cron/cron-stac-validate-full.yaml
workflows/raster/README.md
workflows/raster/national-dem.yaml
workflows/raster/standardising.yaml
workflows/stac/README.md
workflows/stac/stac-validate-parallel.yaml

When updating an existing Collection, some `links` `item` (the ones not updated) may not be located in the scratch (or `*/flat/`) directory. This causes a recursive stac-validation on the Collection to fail (the system can't locate the linked Items as their path is relative). This PR takes the approach of validating the Collection not recursively (excluding its links) and validating every single STAC Items that have been created and saved in the scratch directory during the process. _The already published STAC documents are validated on a regular basis._
- Allow `stac-validate-parallel` to validate any file, not only Collections
- A temporary solution of validating any JSON files has been implemented as the scratch directory has only STAC document as JSON files. This could be fixed by …

feat: validate STAC of only updated files TDE-1359

---

workflows/raster/national-dem.yaml

The `create-collection` task in the `national-dem` workflow is missing the `flat/` directory to be specified.
- specify the `flat/` directory in the location passed to `create-collection` template.
Argo Workflows

fix: location for create-collection is missing flat dir

---

workflows/cron/cron-national-dem.yaml

Updating an existing Collection had been fixed so we can turn this cron job back on.
- remove the `suspend` to be act to its default `false` value.

feat: turn national-dem cron job back on TDE-1440

---

docs/configuration.md
docs/training/examples/wf_output_parallel.yaml
docs/training/workshop.md
templates/argo-tasks/copy.yml
templates/argo-tasks/generate-path.yml
templates/argo-tasks/group.yml
templates/argo-tasks/push-to-github.yml
templates/argo-tasks/stac-setup.yml
templates/argo-tasks/stac-validate.yml
templates/argo-tasks/tile-index-validate.yml
workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/mapsheet-json.yaml
workflows/basemaps/vector-etl.yaml
workflows/raster/national-dem.yaml
workflows/stac/stac-validate-parallel.yaml
workflows/test/flatten.yaml
workflows/test/list.arm.yaml
workflows/test/list.yaml
workflows/util/create-thumbnails.yaml

Some containers specify a `ENTRYPOINT` by using "command" we override the entrypoint, argo-tasks is about to change its `ENTRYPOINT` which would require this repository to update too, however if we do not override the `ENTRYPOINT` here we when argo-tasks updates its entrypoint there will be no changes required here.
Remove all `command` overrides for `argo-tasks` 
run a few testing workflows with and without the `command` ovveride.

refactor: remove command override for containers that specifiy a entrypoint

---

workflows/raster/README.md
workflows/raster/merge-layers.yaml
workflows/raster/national-dem.yaml
workflows/raster/publish-odr.yaml
workflows/raster/standardising.yaml

Publish to ODR workflow currently ignores the `odr_url` pointing to the existing dataset.
- Added `odr_url` input parameter to `publish-odr` workflow and made `generate-path` an optional step.
- Modified `standardising`, `national-dem` and `merge-layers` workflows to pass through `odr_url` when calling `publish-odr`.
- updated readme.
Manual verification of modified `publish-odr` workflow.

fix: publish to ODR to accept odr_url TDE-1447

---

workflows/raster/hillshade.yaml

Github actions - argo linter failed:
```
workflows/raster/hillshade.yaml:
✖ in "hillshade" (WorkflowTemplate): templates.main.tasks.publish-odr failed to resolve {{inputs.parameters.odr_url}}
```
Added `odr_url` to publish_to_odr workflow step in hillshade.yaml
`argo lint --offline templates/ workflows/`

fix: missing odr_url parameter

---

templates/argo-tasks/create-manifest.yml

This one got missed here https://github.com/linz/topo-workflows/pull/985
Some containers specify a `ENTRYPOINT` by using "command" we override the entrypoint, argo-tasks is about to change its `ENTRYPOINT` which would require this repository to update too, however if we do not override the `ENTRYPOINT` here we when argo-tasks updates its entrypoint there will be no changes required here.
Remove all `command` overrides for `argo-tasks` 
run a few testing workflows with and without the `command` ovveride.

refactor: remove command override for containers that specifiy entrypoint

---

templates/topo-imagery/README.md
templates/topo-imagery/generate-hillshade.yaml
workflows/raster/hillshade.yaml

When updating an existing hillshade dataset, the ODR URL needs to be passed to the `generate_hillshade.py` script so the update can be done rather than creating new STAC. Related to https://github.com/linz/topo-imagery/pull/1310
Pass ODR URL to the hillshade template
Submitted test workflow

fix: pass odr_url to the hillshade task TDE-1452

---

workflows/basemaps/imagery-import-cogify.yml

We got a `base-zoom-offset` parameter in cogify cover command that help adjusting the base zoom level of the output COGS.
It should be helpful to include that parameter as optional setting for the imagery import workflow
Add optional `base_zoom_offset` workflow paramter
Running workflow with the parameter that been used.
https://argo.linzaccess.com/workflows/argo/test-basemaps-imagery-import-cogify-base-zoom-offset-m28dw?tab=workflow&nodeId=test-basemaps-imagery-import-cogify-base-zoom-offset-m28dw-2458250471&nodePanelView=containers&uid=80836cfd-17a9-4da3-9def-3c656a8942ca

feat(basemaps): Add base zoom offset for the basemaps imagery import workflow

---

workflows/raster/standardising.yaml

The `imagery-standardising` workflow is not passing the ODR URL properly to the `publish-odr` task. 
- pass the ODR URL from the workflow parameters.

fix: ODR URL is not passed to publish-odr task TDE-1459

---

templates/topo-imagery/README.md
templates/topo-imagery/create-collection.yaml
workflows/raster/hillshade.yaml
workflows/raster/national-dem.yaml

Some datasets, such as National DEM and National DEM Hillshades, get updated regularly but need their title to remain the same (for example they don't include dates, which are added by the automatic title generation).
- Pass the [`--keep-tile=true` parameter to the create-collection step](https://github.com/linz/topo-imagery/pull/1313)  when called by the `national-dem` and `hillshade` workflows. Default to `--keep-title=false`.
Manually ran Workflows.

feat: allow to keep title of existing Collection TDE-1444

---

templates/argo-tasks/README.md
templates/argo-tasks/identify-updated-items.yaml
workflows/raster/hillshade.yaml
workflows/raster/merge-layers.yaml

As a data maintainer, when updating a national DEM Hillshade, I would like to recreate the hillshade tiles only for the nationally combined DEM tiles that have changed from the previous update.
Added a workflow template `identify-updated-items` to call a new argo-workflows command (see https://github.com/linz/argo-tasks/pull/1207).
Updated existing workflows in `hillshade.yaml` and `merge-layers.yaml` to use the new template instead of `tile-index-validate`.

feat: use `derived_from` checksum to see if tile needs re-creating TDE-1449

---

workflows/raster/national-dem.yaml

The `national-dem` workflow is not passing the ODR URL properly to the publish-odr task.
Access the ODR URL from the workflow parameters instead of input parameters.

fix: odr_url not passed to publish-odr task in national-dem workflow TDE-1463

---

workflows/raster/README.md
workflows/raster/hillshade-combinations.yaml
workflows/raster/hillshade.yaml

As a Basemaps user
I want national DSM hillshades (1m and unspecified resolution, standard and igor)
So that I can view/accentuate terrain detail in a variety of basemaps.
- added `hillshade-combinations` workflow template to iterate over preset and DEM/DSM as needed.
- modified `hillshade` workflow template to work with both DEM and DSM datasets
Manual workflow runs

feat: add DSM support to hillshade workflow TDE-1455

---

workflows/cron/README.md
workflows/cron/cron-national-dem-hillshades.yaml
workflows/cron/cron-national-dsm-hillshades.yaml

As a Elevation Data Manager
I want the NZ 1m DEM/DSM Hillshade to be updated automatically when new elevation data is published on the ODR
So that our published data remains in sync
New cron workflows to process both hillshade presets for 1m DEM and 1m DSM each.
Manual test runs of workflows

feat: add cron workflows for hillshades TDE-1427

---

workflows/cron/README.md
workflows/cron/cron-national-dem-hillshades.yaml
workflows/cron/cron-national-dsm-hillshades.yaml
workflows/cron/cron-national-merged-dem-hillshades.yaml
workflows/cron/cron-national-merged-dsm-hillshades.yaml
workflows/cron/cron-stac-validate-fast.yaml

Run Hillshade workflows and STAC validation closer together.
Set Hillshade Workflows CRON times to 9:30 am and 12:30 pm.
Set fast STAC validation workflow to run at 3:00 pm.
Argo linter

chore: update cron times for hillshade workflows TDE-1477

---

workflows/raster/merge-layers.yaml

Merge workflow was now failing on partially updated datasets.
Split STAC validate workflow step into two depending on whether an ODR URL was supplied or not.
Manual WF run

fix: split STAC validate workflow TDE-1475

---

infra/eks/cluster.ts

Give Argo Workflows read access to the two new ODR buckets `nz-coastal` and `nz-topography` in the same way as for `nz-elevation` and `nz-imagery`.

feat: add read permissions to new ODR buckets from Argo TDE-1456

---

templates/argo-tasks/stac-setup.yml
workflows/raster/standardising.yaml

Historical imagery dataset have a Historical Survey Number. `stac-setup` needs this information to run when processing a historical dataset. 
- Allow `stac-setup` workflowTemplate to receive the survey ID and pass it to the `linz/argo-tasks` `stac-setup` command
- Pass the Historical Survey Number from the `imagery-standardising` workflow to the `stac-setup` template
Argo Workflows test

fix: survey id is not passed to stac-setup TDE-1503

---

CONTRIBUTING.md
templates/argo-tasks/stac-setup.yml

[linz/argo-tasks](https://github.com/linz/argo-tasks) uses [`cmd-ts`](https://github.com/Schniz/cmd-ts/) which seems to have an issue when an optional parameter is passed with no value at the end of the command.
- conditionally pass the argument
- add documentation for best practices
Argo Workflows run

fix: stac-setup is failing when survey_id has no value TDE-1509

---

README.md
workflows/test/sleep.yml

For debugging, it can be useful to run a pod to a specific node.
- Document the process
- Add an example
Tested in Argo Workflows

docs: running a pod to a specific node

---

README.md
docs/configuration.md
tools/generate-argo-cli-commands-elevation.py
workflows/basemaps/README.md
workflows/raster/README.md

`s3://linz-workflow-artifacts` bucket has been deleted.
- replace `linz-workflow-artifacts` occurrences to `linz-workflows-scratch`
Search and Replace

chore: remove references to linz-workflow-artifacts bucket TDE-1502

---

templates/argo-tasks/archive-setup.yaml
templates/argo-tasks/copy.yml
workflows/basemaps/topo-maps-standardising.yml
workflows/raster/README.md
workflows/storage/README.md
workflows/storage/archive.yaml
workflows/storage/copy.yaml

In order to save cloud storage costs, the Data Managers should be able to move source data that have already been processed to a designated archive bucket with a Glacier Deep Archive lifecycle policy. The source data would be deleted and non-current versions expired after a set date (as per source bucket configuration).
- Add a `workflowTemplate` `tpl-at-archive-setup` to call the [`linz/argo-tasks/archive-setup`](https://github.com/linz/argo-tasks/pull/1218) command
- Add a `archive` `workflowTemplate` to allow the Data Managers to archive files.
- Give `tpl-at-copy` `workflowTemplate` the ability to compress destination data with `--compress=false/true` option
- Give `tpl-at-copy` `workflowTemplate` the ability to delete source data with `--delete-source=false/true` option
- Move `copy` …

feat: archive workflow TDE-1484

---

workflows/cron/cron-national-dem-coastal.yaml
workflows/cron/cron-national-dem-hillshades-coastal.yaml

For consistency across CRON workflows, use the same ticket number in metadata and workflow arguments.
Added ticket number to `cron-national-dem-coastal` and fixed ticket number in `cron-national-dem-hillshades-coastal`.
n/a

fix: consistent ticket numbers within each workflow

---

docs/infrastructure/components/cloudflared.md
infra/charts/cloudflared.ts

Keeping `cloudflared` up to date.
- Add the latest version (as today) of `cloudflared` image to the AWS ECR.
- Point `cloudflared` deployment to the new image
Successfully deployed on NonProd cluster

feat: upgrade cloudflared image TDE-1560

---

infra/charts/argo.workflows.ts
infra/charts/event.exporter.ts
infra/charts/fluentbit.ts
infra/charts/karpenter.ts

Add PriorityClass to the Argo server / controller and other components to keep them from getting evicted in favour of workflow runners.
Set Argo Workflows Server and Workflow Controller to priorityClass `high-priority`
Set Karpenter, Fluentbit, Event Exporter to priorityClass `very-high-priority`
Successfully synth'd yaml.
Manual testing on Dev cluster.

feat: apply priority class TDE-1564

---

workflows/basemaps/topo-maps-standardising.yml

update to use new cli container v8
* use cli container v8
* fix copy workflow(needed to pass transform arg)
https://argo.linzaccess.com/workflows/argo/topo-raster-maps-standardising-l758f?tab=workflow&nodeId=topo-raster-maps-standardising-l758f-3909996927

fix(basemaps): update topo-maps-standardising to use new cli v8 BM-1279

---

infra/charts/cloudflared.ts

Avoid cloudflared pods to be evicted before workflows runner
- add `high-priority` priorityClass to cloudflared pods
add the priorityclass to the pod specs

feat: add priority class high-priority to cloudflared TDE-1569

---

infra/charts/event.exporter.ts

Since the deployment of https://github.com/linz/topo-workflows/pull/1037, event exporter is not loading its config properly. Seems to be an issue with the helm chart default `layout: {}`
- apply the entire configuration
deployed

fix: event-exporter config

---

templates/topo-imagery/README.md
templates/topo-imagery/create-collection.yaml
workflows/cron/cron-national-merged-dem-hillshades.yaml
workflows/raster/merge-layers.yaml

:mega: **Note:** linked to https://github.com/linz/topo-imagery/pull/1338 which should be merged and released before this PR is merged.
The DEM merged hillshades need a custom description in the same way that some datasets need a custom title. Add an option to keep existing descriptions (load them from the ODR URL).
Added a new flag `--keep-description` when updating the collection for the merged hillshades.
Tested with a workflow. The collection was created with the existing description.

feat: use existing description for merged DEM hillshades TDE-1498

---

templates/argo-tasks/stac-validate.yml
workflows/basemaps/vector-etl-shortbread.yaml

1. Support stac validation in the Shortbread ETL workflow to ensure we validate the stac files before publish to ODR.
2. Support stac validation for all the stac file created from extract command in the mbitile cache bucket.
Passing the new created stac collection.json that enable validate the stac collection and stac item recursively. 
https://argo.linzaccess.com/workflows/argo/test-basemaps-vector-etl-shortbread-stac-pqvcp?tab=workflow&nodeId=test-basemaps-vector-etl-shortbread-stac-pqvcp-4003221865&nodePanelView=inputs-outputs&uid=870c6422-5dc6-4333-9e22-2ba266fce6c7

feat(basemaps): Add stac-validate for shortbread ETL workflow. BM-1307

---

templates/basemaps/cogify.yml
templates/basemaps/create-pull-request.yml
workflows/basemaps/imagery-import-cogify.yml
workflows/basemaps/vector-etl-shortbread.yaml
workflows/basemaps/vector-etl.yaml

Move the cogify and create-pull requests as template, so that we can reuse them in other workflows.
The main reasons to move these are enable reuse of cogify for topo-raster and the new charts import workflow.
So that we don't need to trigger another workflow after topo-raster workflow, we can directly import into basemaps in one workflow.
Existing [topo raster import](https://toitutewhenua.atlassian.net/wiki/spaces/LTS/pages/1119879649/Basemaps+Topo+Raster+NZ+Topo+50k+250k) steps. 
We will need to triger at least three workflows for the import, and it going to be much more if we support pacific islands.
We could refactoring this into a new workflow, and just trigger single workflow and do the full import.
Test on [imagery import …

feat(basemaps): Move the cogify and create-pull-requests into workflow template. BM-1335

---

templates/argo-tasks/README.md
templates/argo-tasks/copy.yml
workflows/storage/README.md

`copy` workflows sometimes get stuck. 
The `tpl-copy` [template](https://github.com/linz/topo-workflows/blob/master/templates/argo-tasks/README.md#argo-taskscopy---tpl-copy) now times out after 15 minutes (using `activeDeadlineSeconds`) and will retry up to 10 times. This is a measure to avoid having to manually interact with the workflows while we investigate the root cause of this issue.
Added `activeDeadlineSeconds` and `retryStrategy` to `tpl-copy` workflow template. 
```yaml
activeDeadlineSeconds: '900' # Run up to 900 secs / 15 minutes
retryStrategy:
limit: '10' # Retry up to 10 times
retryPolicy: 'Always'
```
Manual workflow runs with failing and succeeding workflows.

feat: timeout copy workflow after 15 minutes TDE-1593

---

templates/basemaps/cogify.yml
workflows/basemaps/charts-import-cogify.yml
workflows/basemaps/imagery-import-cogify.yml

We need an argo workflow to standardise and import the charts map from `s3://linz-hydrographic-upload/charts/` into basemaps.
The workflow will run into two steps. 
1. Run `chart` cli, to standardises the charts map that apply cutlines and remove the edges effects.
2. Run `cogify` to import the standardised tif file files and import into basemaps.
3. Skip create-pr, as this will be a single import and manually create basemaps configurations. We can add create-pr later once all imported and require to regular imports in future.
https://argo.linzaccess.com/workflows/argo/test-basemaps-charts-import-cogify-mksjd?tab=workflow&nodeId=test-basemaps-charts-import-cogify-mksjd-579534913&nodePanelView=inputs-outputs&uid=aab06dda-d2a6-4dad-a8d0-d6ba4a69eb0b

feat(basemaps): New workflow to import chart map into basemaps. BM-1339

---

workflows/storage/archive.yaml
workflows/storage/temp-archive-custom-target.yaml

Added imagery and elevation staging permissions to the temp archive command.
Removed a space between the config paths that caused a failure when reading the config files.
Also trimmed white space in source and target to prevent potential copy and paste issues.
Tested on a workflowTemplate in Argo Workflows.

fix: add permissions, remove space in configs and trim inputs TDE-1605

---

workflows/storage/temp-archive-custom-target.yaml

It is occasionally necessary to (carefully) archive a first level directory for some of the smaller sets of data.
Allow bypassing the path check
Tested on Argo Workflows nonprod environment.

fix: allow path check bypass TDE-1605

---

workflows/cron/cron-national-dem-coastal.yaml

The national DEM coastal cron workflow is not following the naming convention of our cron workflows.
rename to `cron-national-dem-coastal`

fix: national-dem-coastal name should start with cron-

---

templates/argo-tasks/delete-empty-folders.yaml
workflows/storage/README.md
workflows/storage/archive.yaml
workflows/storage/copy.yaml

After running the `archive` workflow, some "folders" can remain (if they have been created from the S3 Console) even if the source files have been deleted. This is using https://github.com/linz/argo-tasks/pull/1254.
Add a step in the archive workflow.
Argo Workflows

feat: cleanup empty folders after archiving TDE-1628

---

templates/argo-tasks/README.md
templates/argo-tasks/copy.yml
templates/argo-tasks/list.yaml
templates/argo-tasks/verify-restore.yaml
templates/common/README.md
templates/common/read.file.yaml
workflows/cron/README.md
workflows/cron/cron-copy-restore.yaml
workflows/storage/README.md
workflows/storage/check-restore-copy.yaml
workflows/storage/copy-restore.yaml
workflows/storage/copy.yaml

As a Data Manager I want to move data from the `linz-topographic-archive` / `linz-hydrographic-archive` bucket to a designated bucket so that I can unarchive data when it is required again
This PR contains a cron job that triggers a copy-restore workflow. This lists outstanding S3 Glacier Batch Restore request manifests (without the suffix `.done`) and uses the Argo Tasks `verify-restore` command to check the status of the files referenced in the restore manifests. Once all the files are restored they are copied to the relevant sharing bucket.
Tested on Argo Workflows nonprod and prod environments.

feat: verify restore and copy files TDE-1592

---

templates/argo-tasks/README.md
templates/argo-tasks/stac-setup.yml
templates/argo-tasks/tile-index-validate.yml
workflows/raster/README.md
workflows/raster/hillshade.yaml
workflows/raster/merge-layers.yaml
workflows/raster/national-elevation.yaml
workflows/raster/standardising.yaml

As an imagery maintainer
I want to make sure the GSD specified in metadata is consistent with the resolution of all TIFF images of a survey
`standardising` workflow uses GSD as determined by `tile-index-validate` (`stac-setup` step now depends on `tile-index-validate`). 
`stac-setup` validates GSD against existing data.
Updated all workflows to include new `validate` parameter for `stac-setup`.
Updated readme files.
Argo linter and manual standardising workflow runs with imagery and DEM.

feat: use GSD from tileindex validate and remove user input TDE-1653

---

workflows/raster/standardising.yaml

To make sure GSD is consistent across all TIFFs of a dataset, let users scale TIFF resolutions to be consistent.
Added existing `scale_to_resolution` parameter to `standardising` workflow (optional - based on `retile` flag).
Argo linter and manual workflow runs.

feat: optionally scale resolution of TIFFs to GSD TDE-1658

---

templates/argo-tasks/README.md
templates/argo-tasks/copy.yml
workflows/storage/README.md

Reverts linz/topo-workflows#1054 as the underlying issue should now be resolved since chunkd has been upgraded.

revert: feat: timeout copy workflow after 15 minutes TDE-1593
