linz/topo-workflows

workflows/imagery/tests.yaml
This change allows to run a test script using the Topo-Imagery container (and its dependencies).
- An Argo Workflow `tests.yaml` has been added providing a template to deploy a custom script.
=> feat(topo-imagery): run scripts with topo-imagery container for tests

.github/CODEOWNERS, .kodiak.toml
Add a kodiak config so we can automerge
=> build: merge with a 🚀

workflows/imagery/standardising.yaml
- Fixed the missing name in the config file.
- Add group chunked size for the list-aws.
=> feat(workflow): Version bump for the basemaps cli container.

workflows/imagery/standardising.yaml
see temporary test workflow called: `mdavidson-test-imagery-standardising-v0.2.0-48`
=> feat: add flatten, collection and validate stac to standardise workflow TDE-514

workflows/imagery/standardising.yaml
https://argoproj.github.io/argo-workflows/fields/#fields_29
=> fix: argo parameter value should be string

workflows/imagery/non-visual-qa.yaml, workflows/imagery/standardising.yaml, workflows/imagery/tests.yaml
related https://github.com/linz/topo-imagery/pull/211
=> chore: use arguments with dashes TDE-558

workflows/imagery/standardising.yaml
=> fix: update default parallelism TDE-547

workflows/basemaps/create-config.yaml, workflows/basemaps/imagery-import.yaml, workflows/basemaps/mapsheet-json.yaml, workflows/imagery/publish-copy.yaml, workflows/imagery/standardising.yaml, workflows/imagery/tileset-validate.yaml, workflows/stac/stac-validate.yaml, workflows/test/flatten.yaml
Limited to WorkflowTemplates where user mistake is more likely to happen
=> feat: trim parameter value TDE-629

workflows/basemaps/imagery-import.yaml, workflows/imagery/publish-copy.yaml
https://toitutewhenua.atlassian.net/browse/TDE-627
Add basemaps import step to standardise-publish workflow.
These initial changes are required or the main PR will fail the checks.
=> chore: pre-requisite changes for TDE-627 Workflow to pass GH actions checks

config/semaphores.yml, workflows/imagery/standardising-publish-import.yaml
For bulk processing from the command line
=> feat: add bulk semaphore TDE-654

workflows/imagery/README.md
https://github.com/linz/topo-imagery/pull/489
=> docs: update create_stac.py path

workflows/basemaps/imagery-import-cogify.yml
Add create-pull-request task into cogify workflow to create pull request in basemaps-config repo after importing imagery
Add category and individual parameter for customise the config in pull requests.
Add pull request parameter to decide whether to create it.
*If not applicable, provide explanation of why.*
=> feat(basemaps): Add create-pr task into cogify basemaps imagery import

templates/argo-tasks/copy.yml, workflows/imagery/publish-copy.yaml
https://github.com/linz/topo-workflows/actions/runs/6399176659/job/17370863781
=> fix: missing default input fix

CONFIGURATION.md, docs/training_workshop/ARGO_WORKFLOWS.md, docs/training_workshop/example_workflows/wf_hello_world.yaml, docs/training_workshop/example_workflows/wf_hello_world_args.yaml, docs/training_workshop/example_workflows/wf_hello_world_args_tasks.yaml, docs/training_workshop/example_workflows/wf_hello_world_dag.yaml, docs/training_workshop/example_workflows/wf_output_parallel.yaml, templates/argo-tasks/README.md, templates/argo-tasks/copy.yml, templates/argo-tasks/create-manifest.yml, templates/argo-tasks/group.yml, templates/argo-tasks/push-to-github.yml, templates/argo-tasks/tile-index-validate.yml, workflows/basemaps/imagery-import-cogify.yml, workflows/basemaps/mapsheet-json.yaml, workflows/basemaps/vector-etl.yaml, workflows/imagery/ascii-standardise-publish.yaml, workflows/imagery/standardising.yaml, workflows/imagery/tests.yaml, workflows/stac/stac-validate.yaml, workflows/test/env.yaml, workflows/test/flatten.yaml, workflows/test/list.yaml, workflows/tiv.yml, workflows/util/create-thumbnails.yaml
**motivation:**
update ecr container references to new locations
**modification:**
update ecr container references to new locations
=> feat: use new ecr containers TDE-896

infra/README.md
Update documentation with debug command
add debug command to docs
~~- [ ] Tests updated~~ dont need to test docs
=> docs: add debug command TDE-902

infra/cdk8s.ts, infra/charts/cloudflared.ts, infra/util/ssm.ts, package-lock.json, package.json
To provide secure external access to the Argo server import a cloudflared tunnel
Imports the CDK8s configuration for cloudflared
=> feat: add cloudflared for remote access to argo

.github/workflows/main.yml, infra/charts/karpenter.ts, package-lock.json, package.json
To keep our cluster up to date, we need a automated deployment pipeline so that developers are not required to manually deploy changes after they have been merged into master.
Adds a basic CICD process that uses a CDK/k8s diff on pull request and deploys when merged to master
=> ci: add cicd process for aws-cdk/cdk8s TDE-928

.github/dependabot.yml
Ensure that all CDK-related packages are updated together, for safety.
=> feat: Group dependency updates

docs/infrastructure/kubernetes.version.md
A couple of small issues in this documentation.
see files changed
=> docs: fix kubernetes.version readme

docs/infrastructure/kubernetes.version.md
Understanding why we also need to upgrade the nodes.
Link to official documentation.
=> docs: add more information about cycling EC2 nodes

README.md, docs/training/workshop.md
_What does this change aim to achieve?_
_Why is this change being made? What implications or other considerations are there?_
=> docs: Fix obsolete flag

docs/training/workshop.md
Ensure that the workshop YAML files are the same as the actual files in the repo.
=> docs: Sync linked YAML files with the originals TDE-917

docs/configuration.md
Produce a working table of contents.
=> docs: Fix table of contents

docs/infrastructure/kubernetes.version.md
Give information to the maintainer about a step that takes some time to run
Update doc
=> docs: give information about step taking time

package-lock.json, package.json
we need a version tag to allow git to tag resources properly
create a v0.0.2 version.
=> release: v0.0.2

.github/workflows/main.yml, .github/workflows/pull-request.yml
See
<https://github.com/dependabot/dependabot-core/issues/4691#issuecomment-1296532496>.
=> fix: Use action comments compatible with Dependabot TDE-934

.github/workflows/main.yml, infra/README.md
Tidy and reinstate main github action after cluster changes
- reinstatant argo deploy steps 
- restrict infra steps to only if changes in folder
=> ci: update main.yml gh action TDE-947

workflows/basemaps/imagery-import-cogify.yml, workflows/basemaps/imagery-import.yaml, workflows/raster/README.md, workflows/raster/ascii-standardise-publish.yaml, workflows/raster/publish-copy.yaml, workflows/raster/publish-odr.yaml, workflows/raster/standardising-publish-import.yaml, workflows/raster/standardising.yaml
A ticket (JIRA ticket) ID is a useful information to link to a workflow for filtering purpose.
Ticket is passed as a parameter of the workflow to the `linz.govt.nz/ticket` label value. If no label specified in the parameter, its value is empty (which is fine according to [Kubernetes documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)) but the label is still created.
=> feat: add ticket label to imagery related workflows TDE-956

docs/labels.md, workflows/basemaps/create-config.yaml, workflows/basemaps/create-overview-all.yaml, workflows/basemaps/create-overview.yaml, workflows/basemaps/imagery-import-cogify.yml, workflows/basemaps/imagery-import.yaml, workflows/basemaps/mapsheet-json.yaml, workflows/basemaps/vector-etl.yaml, workflows/raster/ascii-standardise-publish.yaml, workflows/raster/publish-copy.yaml, workflows/raster/publish-odr.yaml, workflows/raster/standardising-publish-import.yaml, workflows/raster/standardising.yaml, workflows/raster/tests.yaml, workflows/stac/stac-validate.yaml, workflows/test/env.yaml, workflows/test/flatten.yaml, workflows/test/list.arm.yaml, workflows/test/list.yaml, workflows/test/sleep.yml, workflows/tiv.yml, workflows/util/create-thumbnails.yaml
Enable Argo users to filter workflow runs easily.
=> feat: Label workflows TDE-843

templates/argo-tasks/push-to-github.yml
_What does this change aim to achieve?_
_Why is this change being made? What implications or other considerations are there?_
=> fix: push to github use PAT TDE-940

infra/README.md
Having a configured environment to be able to deploy the infrastructure.
Add missing prerequisites.
=> docs: infrastructure deployment prerequisites

workflows/raster/standardising.yaml
Add new Elevation providers.
In preparation for processing Elevation datasets.
=> chore: add new Elevation providers TDE-997

workflows/raster/README.md
=> fix: `historic_survey_number` parameter name typos

workflows/raster/README.md, workflows/raster/copy.yaml, workflows/raster/publish-odr.yaml, workflows/raster/standardising-publish-import.yaml
https://github.com/linz/topo-imagery/pull/758
see changes
=> feat: include capture-area.geojson into file copy processes TDE-965

README.md
Make it easier to follow the instructions.
=> docs: Clean up developer instructions

workflows/basemaps/imagery-import-cogify.yml, workflows/basemaps/mapsheet-json.yaml
Upgrade the cli version to the latest releases.
- basemaps cli to v7
- argo tasks cli to v3
- create-overview remains as v6 which is disabled in v7 until we re-implement in cogify.
=> feat(basemaps): Upgrade the basemaps cli version in the workflow

workflows/basemaps/vector-etl.yaml, workflows/cron/cron-vector-etl-roads-addressing.yaml, workflows/cron/cron-vector-etl.yaml
The new version of vector etl container to which include the fix of road addressing big tiles, and include the title into stac file.
- include title in the etl cmd
=> feat(basemaps): Upgrade vector elt include title in the stac. BM-1017

templates/argo-tasks/copy.yml, templates/argo-tasks/create-manifest.yml, templates/argo-tasks/generate-path.yml, templates/argo-tasks/group.yml, templates/argo-tasks/push-to-github.yml, templates/argo-tasks/stac-validate.yml, templates/argo-tasks/tile-index-validate.yml, workflows/basemaps/imagery-import-cogify.yml, workflows/basemaps/mapsheet-json.yaml, workflows/basemaps/vector-etl.yaml, workflows/raster/copy.yaml, workflows/raster/publish-odr.yaml, workflows/raster/standardising.yaml, workflows/stac/stac-validate-parallel.yaml, workflows/test/generate-path.yaml, workflows/util/create-thumbnails.yaml
There is a new version of argo-tasks
Use v4
=> feat: use argo-tasks v4

docs/infrastructure/components/event.exporter.md
Having some basic information about kubernetes-event-exporter deployed in our EKS cluster.
Add some documentation
=> docs: event-exporter component TDE-1194

workflows/raster/publish-odr.yaml, workflows/raster/standardising.yaml
Improve the experience for users who submit Argo workflows using the GUI by offering tooltip help text for each workflow input parameter.
Add description fields to all parameters and update existing descriptions with examples, where appropriate.
=> docs: add descriptions for workflow argument parameters TDE-1222

docs/infrastructure/kubernetes.version.md
List item contents need to be indented to be part of the list item. Otherwise a new list is created for each list item.
=> docs: Fix Markdown formatting TDE-1255

workflows/raster/standardising.yaml
https://github.com/linz/topo-imagery/pull/1120
- add flag to standardising
=> feat: force adding title suffix TDE-1289

docs/local.environment.md, infra/README.md, infra/local.environment.md
It is useful to be able to deploy a Kubernetes cluster locally to do some tests without having to rely on AWS.
Document how to install a K8s cluster locally using `kind`.
=> docs: local cluster environment with Argo Workflows

.github/pull_request_template.md
The current PR template does not exactly align with other of GDE/Basemaps teams repos.
Modify the PR template to match other repos.
=> build: update PR template

workflows/raster/README.md, workflows/raster/hillshade.yaml, workflows/raster/merge-layers.yaml
file-list-content comparison fails
Fix `when` condition before `group`.
Manual workflow runs
=> fix: file-list-content comparison fails TDE-1472

workflows/cron/cron-vector-etl-roads-addressing.yaml
This cron job has to be turned off.
Suspend `cron-vector-etl-roads-addressing` cron workflow
=> chore: turn off cron-vector-etl-roads-addressing

infra/charts/argo.extras.ts, infra/charts/argo.workflows.ts, infra/charts/cloudflared.ts, infra/charts/event.exporter.ts, infra/charts/kube-system.coredns.ts, infra/charts/kube-system.node.local.dns.ts, infra/eks/cluster.ts, package-lock.json, package.json
Stay in standard support / out of extended support for our EKS cluster.
Change all relevant version numbers from 30 to 31 / 1.30 to 1.31
Deployed and updated nonprod cluster and nodes.
=> build: Update EKS from 30 to 31 TDE-1519

workflows/basemaps/vector-etl-shortbread.yaml, workflows/cron/cron-vector-etl-shortbread.yaml
New ETL workflow for shortbead vector map creation include both NZTM and Webmecator.
- New workflow for ETL shortbread
- New cron workflow to trigger this running every Wednesday
https://argo.linzaccess.com/workflows/argo/test-basemaps-vector-etl-shortbread-fjcbh?tab=workflow&uid=16e30b25-71ff-48d2-8588-a5f8de317640
=> feat(basemaps): Shortbread Vector Map Workflow. BM-1232

infra/charts/event.exporter.ts
Keeping `eventexporter` up to date.
Update chart and app version of event exporter. 
Successfully deployed on NonProd cluster
=> feat: upgrade event-exporter TDE-1559

docs/infrastructure/components/priority.class.md, infra/cdk8s.ts, infra/charts/priority.class.ts, infra/constants.ts
Add PriorityClass to the cluster so it can later be applied to Argo server / controller to keep them from getting evicted in favour of workflow runners.
Added PriorityClass definitions.
Manual testing on Dev cluster.
=> feat: add PriorityClass to Cluster TDE-1564

infra/charts/cloudflared.ts
Update `cloudflared` version label to `2025.6.1` for consistency. Cosmetic change.
=> fix: cloudflared version label TDE-1577

workflows/basemaps/topo-maps-standardising.yml
Updating our [Topo Raster Basemap] is a pain. Our [current strategy] requires three steps to process and import a single data source collection into Basemaps:
- Generate STACs (`topo-raster-maps-standardising`)
- Create COGs (`basemaps-imagery-import-cogify`)
- Update `topo-raster.json` Tileset Config (manual)
[Topo Raster Basemap]: https://basemaps.linz.govt.nz/?style=topo-raster&i=topo-raster
[current strategy]: https://toitutewhenua.atlassian.net/wiki/spaces/LTS/pages/1119879649/Basemaps+Topo+Raster+NZ+Topo+50k+250k
To import topo50 and 250 for only mainland and chatham islands will require 2 standardising workflow and 4 following workflows, any this could be much more complex once we add pacific islands.
To make the import work simplified, we can add `import_basemaps` parameter as …
=> feat(basemaps): Support import to basemaps for topo raster workflow. BM-1342

.github/workflows/main.yml
Master build is failing as it is unable to modify a role.
remove role from list to deploy.
=> build: remove sso role until permissions are fixed
